// Generated by CoffeeScript 2.7.0
(function() {
  // to add a course:
  // - add entry to course_data object
  // - instantiate Course instance from entry in course_data object
  // - add course to courses array
  // - add course to any course plan's requirements and associated groups
  var CHEM_105, CHEM_106, CHEM_109, CHEM_115, Course, DegreePlan, MATH_112, MATH_114, MATH_215, MATH_216, MATH_312, MATH_345, MSE_120, MSE_221, MSE_315, MSE_350, MSE_357, MSE_372, MSE_374, MSE_451, PHYS_115, PHYS_186, PHYS_205, PHYS_226, PHYS_229, PHYS_231, PHYS_232, PHYS_240, PHYS_255, PHYS_308, PHYS_315, PHYS_332, PHYS_333, PHYS_340, PHYS_350, PHYS_356, PHYS_360, PHYS_361, PHYS_362, PHYS_363, PHYS_365, PHYS_367, PHYS_375, PHYS_430, PHYS_445, PHYS_465, PHYS_486, YearTerm, course, course_data, courses, current_month, current_year, degree_plan_data, degree_plans, first_term, get_course, get_degree_plan, j, len, second_term, today, wizard, year_terms;

  course_data = {
    MATH_112: {
      field: 'MATH',
      number: 112,
      name: 'Precalculus Mathematics',
      lecture_hours: 4,
      lab_hours: 0,
      credits: 4,
      description: 'Prepares students to enter the Math 114, Math 215, Math 216 sequence. Includes absolute value; logarithmic, exponential, and trigonometric functions; inequalities; conic sections; complex numbers; and topics from theory of equations.',
      le: ['S2'],
      requirements: null,
      years_offered: 'all',
      terms_offered: 'all'
    },
    MATH_114: {
      field: 'MATH',
      number: 114,
      name: 'Calculus I',
      lecture_hours: 4,
      lab_hours: 0,
      credits: 4,
      description: 'Limits, theory, and application of the derivative; introduction to integration.',
      le: ['S2'],
      requirements: {
        prereqs: ['MATH 112']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    MATH_215: {
      field: 'MATH',
      number: 215,
      name: 'Calculus II',
      lecture_hours: 4,
      lab_hours: 0,
      credits: 4,
      description: "Applications and techniques of integration; improper integrals; sequences and series; power series and Taylor's formula.",
      le: ['S2'],
      requirements: {
        prereqs: ['MATH 114']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    MATH_216: {
      field: 'MATH',
      number: 216,
      name: 'Calculus III',
      lecture_hours: 4,
      lab_hours: 0,
      credits: 4,
      description: "Introduction to functions of several variables, including partial derivatives, multiple integrals, the calculus of vector-valued functions, and Green's Theorem, Stokes' Theorem, and the Divergence Theorem.",
      le: [],
      requirements: {
        prereqs: ['MATH 215']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    MATH_312: {
      field: 'MATH',
      number: 312,
      name: 'Differential Equations and Linear Algebra',
      lecture_hours: 4,
      lab_hours: 0,
      credits: 4,
      description: "Linear algebra: basis, dimension, matrix algebra, determinants, inverses, systems of linear equations, eigenvalues/eigenvectors. (Optional) matrices as linear transformations. Differential equations: first-order linear, separable; second-order linear with constant coefficients; higher order differential equations; first-order linear systems with constant coefficients; Laplace transforms; power series solutions. (Optional) Proof of Existence and Uniqueness Theorems.",
      le: [],
      requirements: {
        prereqs: ['MATH 215']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    MATH_345: {
      field: 'MATH',
      number: 345,
      name: 'Introduction to Probability and Mathematical Statistics',
      lecture_hours: 4,
      lab_hours: 0,
      credits: 4,
      description: "Counting techniques, discrete and continuous random variables, probability distributions, sampling distributions, estimation, hypothesis testing, linear regression, correlation, nonparametric statistics. Students who desire more extensive probability and statistics should take Math 346/Math 546, Math 347/Math 547.",
      le: [],
      requirements: {
        coreqs: ['MATH 215']
      },
      years_offered: 'all',
      terms_offered: 'fall'
    },
    CHEM_115: {
      field: 'CHEM',
      number: 115,
      name: 'Chemical Principles',
      lecture_hours: 3,
      lab_hours: 6,
      credits: 6,
      description: "Principles of chemistry, including chemical properties and the periodic table, atomic structure, chemical bonding, equilibria, thermodynamics, acid-base reactions, oxidation-reduction reactions and complexation reactions.",
      le: ['K1', 'K1L'],
      requirements: {
        exclude: ['CHEM 105', 'CHEM 106', 'CHEM 109']
      },
      years_offered: 'all',
      terms_offered: 'fall'
    },
    CHEM_105: {
      field: 'CHEM',
      number: 105,
      name: 'General Chemistry I Lecture',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "Principles of chemistry, including atomic structure, physical and periodic properties, structure and bonding, reactions, thermochemistry, and stoichiometry.",
      le: [],
      requirements: {
        exclude: ['CHEM 115']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    CHEM_106: {
      field: 'CHEM',
      number: 106,
      name: 'General Chemistry I Laboratory',
      lecture_hours: 1,
      lab_hours: 2,
      credits: 2,
      description: "A general chemistry lab/discussion experience. Gases, reactions, stoichiometry, solution chemistry, thermochem. Data collection, management, and interpretation.",
      le: ['K1', 'K1L'],
      requirements: {
        coreqs: ['CHEM 105'],
        exclude: ['CHEM 115']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    CHEM_109: {
      field: 'CHEM',
      number: 109,
      name: 'General Chemistry II with Lab',
      lecture_hours: 3,
      lab_hours: 3,
      credits: 4,
      description: "Solution properties and intermolecular forces; equilibrium, thermodynamic and kinetic aspects of chemical reactions; acid-base, precipitation, and redox reactions.",
      le: [],
      requirements: {
        prereqs: ['CHEM 104', 'CHEM 105'],
        exclude: ['CHEM 115']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    MSE_120: {
      field: 'MSE',
      number: 120,
      name: 'Introduction to Engineering',
      lecture_hours: 1,
      lab_hours: 2,
      credits: 2,
      description: "A comprehensive study of the engineering design process. Discussion of engineering disciplines with comparisons. The laboratory portion of the course includes design projects from various engineering disciplines.",
      le: ['S3'],
      requirements: null,
      years_offered: 'all',
      terms_offered: 'all'
    },
    MSE_221: {
      field: 'MSE',
      number: 221,
      name: 'Living in a Materials World',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "Processing and structure’s impact on materials properties and performance. Societal benefits of sustainable, biomimetic, or responsible materials selection.",
      le: [],
      requirements: {
        corez: ['MATH 114']
      },
      years_offered: 'all',
      terms_offered: 'spring'
    },
    MSE_315: {
      field: 'MSE',
      number: 315,
      name: 'Materials Characterization',
      lecture_hours: 2,
      lab_hours: 4,
      credits: 4,
      description: "A survey of commonly used materials characterization methods (XPS, SEM, AFM, XRD, XRF), including their theory of operation and hands-on experience. Includes a discussion of the measurement process and instrumental analysis of samples.",
      le: ['S3'],
      requirements: {
        prereqs: ['PHYS 231'],
        combo: {
          min: 1,
          options: ['CHEM 105', 'CHEM 115']
        }
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    MSE_350: {
      field: 'MSE',
      number: 350,
      name: 'Thermodynamics of Materials',
      lecture_hours: 3,
      lab_hours: 2,
      credits: 4,
      description: "Survey of the laws of thermodynamics and their application in Materials Science including phase equilibria. Mathematical skills relevant to engineering applications are discussed in the lab section.",
      le: [],
      requirements: {
        prereqs: ['MSE 221', 'MATH 215'],
        coreqs: ['PHYS 232'],
        combo: {
          min: 1,
          options: ['CHEM 109', 'CHEM 115']
        }
      },
      years_offered: 'all',
      terms_offered: 'fall'
    },
    MSE_357: {
      field: 'MSE',
      number: 357,
      name: 'Phase Transformation & Kinetics',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "Phase transformations are explored with emphasis on microstructure development, the impact of diffusion, and nucleation/growth mechanisms.",
      le: [],
      requirements: {
        prereqs: ['MSE 221', 'MATH 215'],
        combo: {
          min: 1,
          options: ['CHEM 109', 'CHEM 115']
        }
      },
      years_offered: 'all',
      terms_offered: 'fall'
    },
    MSE_372: {
      field: 'MSE',
      number: 372,
      name: 'Transport Phenomena',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "Principles of momentum, heat, and mass transport. Applications of appropriate differential equations and boundary conditions to solve problems in materials processing.",
      le: [],
      requirements: {
        prereqs: ['MATH 312']
      },
      years_offered: 'all',
      terms_offered: 'spring'
    },
    MSE_374: {
      field: 'MSE',
      number: 374,
      name: 'Electrical, Optical and Magnetic Properties of Materials',
      lecture_hours: 4,
      lab_hours: 0,
      credits: 4,
      description: "A description of the behaviors of crystalline solids. Topics include crystallography, diffraction, and the electrical, optical and magnetic properties of materials. Semiconducting materials and devices will also be discussed.",
      le: [],
      requirements: {
        prereqs: ['PHYS 332']
      },
      years_offered: 'all',
      terms_offered: 'fall'
    },
    MSE_451: {
      field: 'MSE',
      number: 451,
      name: 'Computational Materials Science',
      lecture_hours: 2,
      lab_hours: 3,
      credits: 3,
      description: "Theory and application of computational methods to model, understand and predict the behavior of materials. Labs provide hands-on experience in solving real materials problems using computational approaches. Note: can also take after CHEM 434, which is not part of this databse.",
      le: [],
      requirements: {
        combo: {
          min: 1,
          options: ['PHYS 333', 'MSE 350', 'CHEM 434']
        }
      },
      years_offered: 'all',
      terms_offered: 'spring'
    },
    PHYS_115: {
      field: 'PHYS',
      number: 115,
      name: 'Survey of Astronomy',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "A one-semester presentation of our current understanding of the universe, including the solar system, birth and death of stars, unusual phenomena such as black holes and quasars, evolution of galaxies and the universe, and our link with the cosmos.",
      le: ['K1'],
      requirements: null,
      years_offered: 'all',
      terms_offered: 'all'
    },
    PHYS_186: {
      field: 'PHYS',
      number: 186,
      name: 'Introductory Seminar',
      lecture_hours: 0.5,
      lab_hours: 0,
      credits: 0.5,
      description: "Students will explore avenues for obtaining an internship, discuss plans for participating in the required research project, attend the weekly Physics Seminar, develop academic plans, and participate in postgraduate planning.",
      le: [],
      requirements: null,
      years_offered: 'all',
      terms_offered: 'fall'
    },
    PHYS_205: {
      field: 'PHYS',
      number: 205,
      name: 'Physics of Renewable Energy',
      lecture_hours: 3,
      lab_hours: 2,
      credits: 4,
      description: "Explores the basic physics principles behind various types of renewable energy sources. Discusses impact renewable energy sources have on mitigating global warming and climate change.",
      le: ['K1', 'K1L', 'R3'],
      requirements: null,
      years_offered: 'all',
      terms_offered: 'fall'
    },
    PHYS_226: {
      field: 'PHYS',
      number: 226,
      name: 'Astronomy-Solar System',
      lecture_hours: 3,
      lab_hours: 2,
      credits: 4,
      description: "The physical nature of the solar system, including earth motions, celestial coordinates, time, telescopes, moon, planets, sun, and origin of solar system.",
      le: ['K1', 'K1L', 'I1'],
      requirements: null,
      years_offered: 'all',
      terms_offered: 'fall'
    },
    PHYS_229: {
      field: 'PHYS',
      number: 229,
      name: 'Astronomy-Stars and Galaxies',
      lecture_hours: 3,
      lab_hours: 2,
      credits: 4,
      description: "The physical nature of the universe, including stellar evolution, multiple and variable stars, the Milky Way galaxy, other galaxies, and origin of the universe.",
      le: ['K1', 'K1L'],
      requirements: null,
      years_offered: 'all',
      terms_offered: 'spring'
    },
    PHYS_231: {
      field: 'PHYS',
      number: 231,
      name: 'University Physics I',
      lecture_hours: 4,
      lab_hours: 2,
      credits: 5,
      description: "Physics for science and engineering students, including the study of mechanics, simple harmonic motion, and wave motion.",
      le: ['K1', 'K1L'],
      requirements: {
        coreqs: ['MATH 114']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    PHYS_232: {
      field: 'PHYS',
      number: 232,
      name: 'University Physics II',
      lecture_hours: 4,
      lab_hours: 2,
      credits: 5,
      description: "A continuation of Physics 231, including the study of electricity, magnetism, and optics.",
      le: ['K1', 'K1L'],
      requirements: {
        coreqs: ['MATH 215'],
        prereqs: ['PHYS 231']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    PHYS_240: {
      field: 'PHYS',
      number: 240,
      name: 'Computational Physics',
      lecture_hours: 2,
      lab_hours: 2,
      credits: 3,
      description: "An introduction to the use of computational tools for solving physical problems. Topics include an introduction to computing, visualization techniques, numerical integration, and numerical solutions to differential equations.",
      le: [],
      requirements: {
        prereqs: ['PHYS 231']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    PHYS_255: {
      field: 'PHYS',
      number: 255,
      name: 'Statics',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "Designed primarily for pre-engineering students. Includes static equilibrium of rigid bodies, centroids, analysis of structures, friction, and moments of inertia.",
      le: [],
      requirements: {
        prereqs: ['PHYS 231'],
        coreqs: ['MATH 215']
      },
      years_offered: 'all',
      terms_offered: 'fall'
    },
    PHYS_308: {
      field: 'PHYS',
      number: 308,
      name: 'Science of Musical Sound',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "Physical concepts related to production of tones and speech. Application to musical instruments and auditorium acoustics, with experimental demonstrations of vibrational phenomena and electronic sound analysis and synthesis. No prior physics or university mathematics assumed.",
      le: ['K1'],
      requirements: null,
      years_offered: 'all',
      terms_offered: 'spring'
    },
    PHYS_315: {
      field: 'PHYS',
      number: 315,
      name: 'The Mysterious Universe',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "A view of the world as revealed by contemporary physical thought. Topics include size and origin of universe, ultimate nature of matter; modern ideas of space, time and energy; possibilities of extraterrestrial life; and values and limitations of science.",
      le: ['K1', 'I1'],
      requirements: null,
      years_offered: 'all',
      terms_offered: 'all'
    },
    PHYS_332: {
      field: 'PHYS',
      number: 332,
      name: 'University Physics III',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "Physics for science and engineering students, including the study of fluids, heat, thermodynamics, relativity, and an introduction to modern physics.",
      le: ['I1'],
      requirements: {
        prereqs: ['PHYS 232', 'MATH 215']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    PHYS_333: {
      field: 'PHYS',
      number: 333,
      name: 'Quantum Physics',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "Introduction to the experimental and theoretical basis of quantum physics, including particle aspects of radiation, matter waves, Bohr model of the atom, Schrodinger wave mechanics and its application to the hydrogen atom and multi-electron atoms.",
      le: [],
      requirements: {
        prereqs: ['PHYS 332', 'MATH 216']
      },
      years_offered: 'even',
      terms_offered: 'fall'
    },
    PHYS_340: {
      field: 'PHYS',
      number: 340,
      name: 'Optics',
      lecture_hours: 3,
      lab_hours: 3,
      credits: 4,
      description: "Lecture and laboratory work cover geometrical and physical optics, image formation, optical instruments, interference, diffraction, polarization, and modern topics including lasers.",
      le: [],
      requirements: {
        prereqs: ['PHYS 232', 'MATH 215']
      },
      years_offered: 'all',
      terms_offered: 'spring'
    },
    PHYS_350: {
      field: 'PHYS',
      number: 350,
      name: 'Electric and Electronic Circuits',
      lecture_hours: 3,
      lab_hours: 3,
      credits: 4,
      description: "General introduction to electrical circuits and electronics including analysis of DC and AC circuits, simple passive filters, diodes, transistors, operational amplifiers, simple digital electronics, and circuit design and construction.",
      le: [],
      requirements: {
        prereqs: ['PHYS 232', 'MATH 215']
      },
      years_offered: 'all',
      terms_offered: 'fall'
    },
    PHYS_356: {
      field: 'PHYS',
      number: 356,
      name: 'Dynamics',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "A continuation of Physics 255. Dynamics of rigid bodies, moments of inertia, work, energy, impulse, and momentum.",
      le: [],
      requirements: {
        prereqs: ['PHYS 255', 'MATH 215'],
        exclude: ['PHYS 356']
      },
      years_offered: 'all',
      terms_offered: 'spring'
    },
    PHYS_360: {
      field: 'PHYS',
      number: 360,
      name: 'Electronics',
      lecture_hours: 3,
      lab_hours: 3,
      credits: 4,
      description: "Description, analysis, and laboratory measurements of digital and analog devices including transistor amplifiers, operational amplifiers, oscillators, gates, flip-flops, analog-digital converters, and microprocessors.",
      le: [],
      requirements: {
        prereqs: ['PHYS 350', 'MATH 240']
      },
      years_offered: 'all',
      terms_offered: 'spring'
    },
    PHYS_361: {
      field: 'PHYS',
      number: 361,
      name: 'LabVIEW Basics',
      lecture_hours: 2,
      lab_hours: 0,
      credits: 2,
      description: "Lecture and laboratory work cover an introduction to the graphical programming language LabVIEW. LabVIEW has been widely adopted as the industry standard for computerized data acquisition, analysis and instrument control.",
      le: [],
      requirements: {
        coreqs: ['PHYS 350']
      },
      years_offered: 'all',
      terms_offered: 'fall'
    },
    PHYS_362: {
      field: 'PHYS',
      number: 362,
      name: 'LabVIEW Applications',
      lecture_hours: 2,
      lab_hours: 0,
      credits: 2,
      description: "Lecture and laboratory exercises cover applications using the graphical programming language LabVIEW. Topics include advanced programming structures, CompactDAQ hardware, digital signal processing, motor control, encoders, PID process control, RS-232 instrument control, component testing, sensor monitoring.",
      le: [],
      requirements: {
        prereqs: ['PHYS 361']
      },
      years_offered: 'all',
      terms_offered: 'spring'
    },
    PHYS_363: {
      field: 'PHYS',
      number: 363,
      name: 'LabVIEW cRIO',
      lecture_hours: 1,
      lab_hours: 0,
      credits: 1,
      description: "Lecture and laboratory exercises cover the theory and application of the cRIO automation controller using the graphical programming language LabVIEW. Topics include Real-Time operating system, field programmable gate array (FPGA) and network shared variables.",
      le: [],
      requirements: {
        coreqs: ['PHYS 362']
      },
      years_offered: 'all',
      terms_offered: 'spring'
    },
    PHYS_365: {
      field: 'PHYS',
      number: 365,
      name: 'Theoretical Mechanics',
      lecture_hours: 4,
      lab_hours: 0,
      credits: 4,
      description: "Newton's laws, accelerated frames, central-force orbits, angular momentum of systems, coupled oscillations, generalized coordinates, and Lagrange's equations.",
      le: [],
      requirements: {
        prereqs: ['MATH 216', 'PHYS 231', 'PHYS 240'],
        exclude: ['PHYS 356']
      },
      years_offered: 'odd',
      terms_offered: 'fall'
    },
    PHYS_367: {
      field: 'PHYS',
      number: 367,
      name: 'Astrophysics',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "Physics applied to astronomical objects. The birth, structure, and evolution of stars are studied in detail. Nebulae, the interstellar medium, and stellar remnants are also investigated.",
      le: [],
      requirements: {
        prereqs: ['PHYS 240', 'PHYS 332']
      },
      years_offered: 'odd',
      terms_offered: 'fall'
    },
    PHYS_375: {
      field: 'PHYS',
      number: 375,
      name: 'Electromagnetic Fields',
      lecture_hours: 4,
      lab_hours: 0,
      credits: 4,
      description: "Electric and magnetic fields, dielectric and magnetic properties of materials, and electromagnetic phenomena. Field theory leading to the development of Maxwell's equations and the plane electromagnetic wave.",
      le: [],
      requirements: {
        prereqs: ['PHYS 240', 'PHYS 332', 'MATH 216', 'MATH 312']
      },
      years_offered: 'even',
      terms_offered: 'spring'
    },
    PHYS_430: {
      field: 'PHYS',
      number: 430,
      name: 'Advanced Laboratory Technique',
      lecture_hours: 0,
      lab_hours: 4,
      credits: 2,
      description: "Laboratory course for students with special interests in experimental physics. The emphasis is on widely applicable modern experimental methods.",
      le: [],
      requirements: {
        combo: {
          min: 1,
          options: ['PHYS 340', 'PHYS 350', 'PHYS 360']
        }
      },
      years_offered: 'all',
      terms_offered: 'fall'
    },
    PHYS_445: {
      field: 'PHYS',
      number: 445,
      name: 'Thermal Physics',
      lecture_hours: 4,
      lab_hours: 0,
      credits: 4,
      description: "Statistical mechanics and thermodynamics including the laws of classical thermodynamics, equations of state, thermodynamical processes, and applications to classical and quantum mechanical systems.",
      le: [],
      requirements: {
        prereqs: ['PHYS 332', 'MATH 216']
      },
      years_offered: 'even',
      terms_offered: 'fall'
    },
    PHYS_465: {
      field: 'PHYS',
      number: 465,
      name: 'Quantum Mechanics',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "A continuation of Physics 333, including Dirac notation, operator methods, one dimensional potentials, spin and angular momentum, and the philosophical interpretation of quantum mechanics.",
      le: [],
      requirements: {
        prereqs: ['PHYS 333', 'MATH 312']
      },
      years_offered: 'odd',
      terms_offered: 'spring'
    },
    PHYS_486: {
      field: 'PHYS',
      number: 486,
      name: 'Senior Seminar',
      lecture_hours: 0.5,
      lab_hours: 0,
      credits: 0.5,
      description: "Students will present a capstone project seminar, develop presentation skills (oral and poster), take a nationally normed test covering undergraduate physics, discuss their post-graduate plans, and assist the department in assessing the major.",
      le: ['S3'],
      requirements: {
        custom: 'Students need to have completed an adviser-approved capstone project before entering this class. This can be accomplished through various means: PHYS 399, PHYS 430, PHYS 495, PHYS 499, through an academic or industrial internship, or through another approved means.'
      },
      years_offered: 'all',
      terms_offered: 'fall'
    }
  };

  Course = class Course {
    constructor(course_info) {
      this.course_info = course_info;
      // unpack course data object
      this.field = this.course_info.field;
      this.number = this.course_info.number;
      this.name = this.course_info.name;
      this.lecture_hours = this.course_info.lecture_hours;
      this.lab_hours = this.course_info.lab_hours;
      this.credits = this.course_info.credits;
      this.description = this.course_info.description;
      this.le = this.course_info.le;
      // designations are strings, regualar values hold actual courses
      // actual courses need to be set up later, since there's not guarantee 
      // the courses already exist, nor is there a way to get at them

      // prereqs: course must be taken BEFORE enrolling
      // coreqs: course must be taken BEFORE or WHILE enrolling
      // prereq_options: some number of these courses must be taken BEFORE enrolling
      // exclude: cannot enroll if any of these courses have been completed
      this.prereq_designations = [];
      this.coreq_designations = [];
      this.combo_option_designations = [];
      this.exclude_designations = [];
      this.prereqs = [];
      this.coreqs = [];
      this.combo_options = [];
      this.combo_option_min = 0;
      this.exclusions = [];
      if (this.course_info.requirements !== null) {
        if (this.course_info.requirements.prereqs !== void 0) {
          this.prereq_designations = this.course_info.requirements.prereqs;
        }
        if (this.course_info.requirements.coreqs !== void 0) {
          this.coreq_designations = this.course_info.requirements.coreqs;
        }
        if (this.course_info.requirements.combo !== void 0) {
          this.combo_option_designations = this.course_info.requirements.combo.options;
          this.combo_option_min = this.course_info.requirements.combo.min;
        }
        if (this.course_info.requirements.exclude !== void 0) {
          this.exclude_designations = this.course_info.requirements.exclude;
        }
      }
      this.years_offered = this.course_info.years_offered;
      this.terms_offered = this.course_info.terms_offered;
      // HTML helpers
      this.context_classes = ['default', 'primary', 'secondary', 'success', 'warning', 'danger', 'thick'];
      this.all_border_classes = (this.context_classes.map(function(cls) {
        return 'border-' + cls;
      })).join(' ');
      this.all_bg_classes = (this.context_classes.map(function(cls) {
        return 'bg-' + cls;
      })).join(' ');
      this.all_btn_classes = (this.context_classes.map(function(cls) {
        return 'btn-' + cls;
      })).join(' ');
      // CSS IDs and Selectors
      this.completed_id = `${this.field}-${this.number}-completed`;
      this.enrolling_id = `${this.field}-${this.number}-enrolling`;
      this.card_id = `${this.field}${this.number}`;
      this.modal_id = `${this.field}-${this.number}`;
      this.completed_sel = '#' + this.completed_id;
      this.enrolling_sel = '#' + this.enrolling_id;
      this.card_sel = '#' + this.card_id;
      this.header_sel = this.card_sel + '>h5.card-header';
      this.modal_sel = '#' + this.modal_id;
      // state variables
      this.completed = false;
      this.enrolling = false;
      this.year_term_taken = false;
      // base HTML card
      this.html_card = `<div class='card' id='${this.card_id}'>\n`;
      this.html_card += `  <h5 class='card-header'>${this.field} ${this.number} <span class='font-italic'>(${this.credits} credits)</span></h5>\n`;
      this.html_card += "  <div class='card-body'>\n";
      this.html_card += `    <h5 class='card-title'>${this.name}</h5>\n`;
      // @html_card += "    <p class='card-text'>#{@description}</p>\n"
      this.html_card += "    <div class='row'>\n";
      this.html_card += "      <div class='col-5'>\n";
      this.html_card += `        <button type='button' class='btn btn-sm description' id='${this.modal_id}'>Details</button>\n`;
      this.html_card += "     </div>\n";
      this.html_card += "      <div class='col-7 px-1'>\n";
      this.html_card += "        <div class='custom-control custom-switch'>\n";
      this.html_card += `          <input type='checkbox' class='custom-control-input completed' id='${this.completed_id}'>\n`;
      this.html_card += `          <label for='${this.completed_id}' class='custom-control-label'>Completed</label>\n`;
      this.html_card += "        </div>\n";
      this.html_card += "        <div class='custom-control custom-switch'>\n";
      this.html_card += `          <input type='checkbox' class='custom-control-input enrolling' id='${this.enrolling_id}'>\n`;
      this.html_card += `          <label for='${this.enrolling_id}' class='custom-control-label'>Enrolling</label>\n`;
      this.html_card += "        </div>\n";
      this.html_card += "      </div>\n";
      this.html_card += "    </div>\n";
      this.html_card += "  </div>\n";
      this.html_card += "</div>";
    }

    toString() {
      return `${this.field} ${this.number}`;
    }

    toggle_completed() {
      return this.completed = !this.completed;
    }

    toggle_enrolling() {
      return this.enrolling = !this.enrolling;
    }

    update_modal(year_term) {
      var availability;
      $('#course-info-label').html(`${this.field} ${this.number}: ${this.name}`);
      $('#course-description').html('');
      $('#course-description').append(`<p>${this.description}</p>`);
      $('#course-description').append(`<p>Lecture Hours: ${this.lecture_hours}; Lab Hours: ${this.lab_hours}</p>`);
      if (this.prereq_designations.length > 0) {
        $('#course-description').append(`<p><span class='font-italic'>Prerequisites:</span> ${this.prereq_designations.join(', ')}</p>`);
      }
      if (this.coreq_designations.length > 0) {
        $('#course-description').append(`<p><span class='font-italic'>Corequisites:</span> ${this.coreq_designations.join(', ')}</p>`);
      }
      if (this.exclude_designations.length > 0) {
        $('#course-description').append(`<p><span class='font-italic'>No credit if taken with/after:</span> ${this.exclude_designations.join(', ')}</p>`);
      }
      if (this.combo_option_designations.length > 0) {
        $('#course-description').append(`<p><span class='font-italic'>Must have taken at least ${this.combo_option_min} of:</span> ${this.combo_option_designations.join(', ')}</p>`);
      }
      availability = 'Offered ';
      if (this.terms_offered === 'all') {
        availability += 'every term.';
      } else if (this.years_offered === 'all') {
        availability += `in the <span class='font-weight-bold'>${this.terms_offered} term</span> every year.`;
      } else {
        availability += `in the <span class='font-weight-bold'>${this.terms_offered} term of ${this.years_offered} years</span>.`;
      }
      $('#course-description').append(`<p>${availability}</p>`);
      return $('#modal-enrolling').prop('disabled', !this.available(year_term) || this.completed);
    }

    // update coreqs and prereqs from list of courses. Uses designations to 
    // query an array of courses, and then makes the actual course objects the
    // prerequisistes, corequisites, etc.
    update_requirements(courses) {
      var course, designation, j, k, l, len, len1, len2, len3, len4, len5, len6, m, n, o, p, ref, ref1, ref2, ref3, results;
      if (this.prereq_designations.length !== 0) {
        ref = this.prereq_designations;
        for (j = 0, len = ref.length; j < len; j++) {
          designation = ref[j];
          for (k = 0, len1 = courses.length; k < len1; k++) {
            course = courses[k];
            if (`${course.field} ${course.number}` === designation) {
              this.prereqs.push(course);
            }
          }
        }
      }
      ref1 = this.coreq_designations;
      for (l = 0, len2 = ref1.length; l < len2; l++) {
        designation = ref1[l];
        for (m = 0, len3 = courses.length; m < len3; m++) {
          course = courses[m];
          if (`${course.field} ${course.number}` === designation) {
            this.coreqs.push(course);
          }
        }
      }
      ref2 = this.combo_option_designations;
      for (n = 0, len4 = ref2.length; n < len4; n++) {
        designation = ref2[n];
        for (o = 0, len5 = courses.length; o < len5; o++) {
          course = courses[o];
          if (`${course.field} ${course.number}` === designation) {
            this.combo_options.push(course);
          }
        }
      }
      ref3 = this.exclude_designations;
      results = [];
      for (p = 0, len6 = ref3.length; p < len6; p++) {
        designation = ref3[p];
        results.push((function() {
          var len7, q, results1;
          results1 = [];
          for (q = 0, len7 = courses.length; q < len7; q++) {
            course = courses[q];
            if (`${course.field} ${course.number}` === designation) {
              results1.push(this.exclusions.push(course));
            } else {
              results1.push(void 0);
            }
          }
          return results1;
        }).call(this));
      }
      return results;
    }

    // find courses that have this course as a direct dependence
    downstream(courses) {
      var course, j, len, res;
      res = [];
      for (j = 0, len = courses.length; j < len; j++) {
        course = courses[j];
        if (course.prereqs.includes(this) || course.coreqs.includes(this)) {
          res.push(course);
        }
      }
      return res;
    }

    available(year_term) {
      var combo_count, combo_option, coreq, course, j, k, l, len, len1, len2, len3, m, prereq, ref, ref1, ref2, ref3, res, term, year;
      year = year_term.year;
      term = year_term.term;
      res = true;
      ref = this.prereqs;
      for (j = 0, len = ref.length; j < len; j++) {
        prereq = ref[j];
        res = res && prereq.completed;
      }
      ref1 = this.coreqs;
      for (k = 0, len1 = ref1.length; k < len1; k++) {
        coreq = ref1[k];
        res = res && (coreq.completed || coreq.enrolling);
      }
      // handle course with a minimum number of prerequisites from a collection
      // of courses
      combo_count = 0;
      ref2 = this.combo_options;
      for (l = 0, len2 = ref2.length; l < len2; l++) {
        combo_option = ref2[l];
        if (combo_option.completed) {
          combo_count += 1;
        }
      }
      res = res && (combo_count >= this.combo_option_min);
      ref3 = this.exclusions;
      // handle courses that exclude other courses (ex. 356 & 365)  
      for (m = 0, len3 = ref3.length; m < len3; m++) {
        course = ref3[m];
        res = res && !(course.completed || course.enrolling);
      }
      // offered this year?
      res = res && ((this.years_offered === 'all') || ((this.years_offered === 'even') && (year % 2 === 0)) || ((this.years_offered === 'odd') && (year % 2 === 1)));
      // offered this term?
      res = res && ((this.terms_offered === 'all') || this.terms_offered === year_term.term);
      return res;
    }

    clear_formatting() {
      $(this.card_sel).removeClass(this.all_border_classes);
      $(this.header_sel).removeClass(this.all_bg_classes);
      $(this.header_sel).removeClass('text-white font-weight-bold');
      return $(this.modal_sel).removeClass(this.all_btn_classes);
    }

    // $(@modal_sel).addClass('btn-secondary')
    mark_available(degree_plan) {
      this.completed = false;
      this.year_term_taken = false;
      this.enrolling = false;
      this.clear_formatting();
      if (degree_plan) {
        if (degree_plan.required(this)) {
          $(this.card_sel).addClass('border-thick');
          $(this.header_sel).addClass('font-weight-bold');
        }
      }
      $(this.card_sel).addClass('border-warning');
      $(this.header_sel).addClass('bg-warning text-white');
      $(this.completed_sel).prop('disabled', false);
      $(this.enrolling_sel).prop('disabled', false);
      $(this.completed_sel).prop('checked', false);
      $(this.enrolling_sel).prop('checked', false);
      return $(this.modal_sel).addClass('btn-warning');
    }

    mark_unavailable(degree_plan) {
      this.completed = false;
      this.year_term_taken = false;
      this.enrolling = false;
      this.clear_formatting();
      if (degree_plan) {
        if (degree_plan.required(this)) {
          $(this.card_sel).addClass('border-thick');
          $(this.header_sel).addClass('font-weight-bold');
        }
      }
      $(this.card_sel).addClass('border-secondary');
      $(this.completed_sel).prop('disabled', false);
      $(this.enrolling_sel).prop('disabled', true);
      $(this.completed_sel).prop('checked', false);
      $(this.enrolling_sel).prop('checked', false);
      return $(this.modal_sel).addClass('btn-secondary');
    }

    mark_completed(year_term, degree_plan) {
      var course, j, k, l, len, len1, len2, ref, ref1, ref2, results;
      this.completed = true;
      this.year_term_taken = year_term;
      this.enrolling = false;
      this.clear_formatting();
      if (degree_plan) {
        if (degree_plan.required(this)) {
          $(this.card_sel).addClass('border-thick');
          $(this.header_sel).addClass('font-weight-bold');
        }
      }
      $(this.card_sel).addClass('border-success');
      $(this.header_sel).addClass('bg-success text-white');
      $(this.completed_sel).prop('checked', true);
      $(this.enrolling_sel).prop('checked', false);
      $(this.completed_sel).prop('disabled', false);
      $(this.enrolling_sel).prop('disabled', true);
      $(this.modal_sel).addClass('btn-success');
      ref = this.prereqs;
      for (j = 0, len = ref.length; j < len; j++) {
        course = ref[j];
        if (!(course.completed && course.year_term_taken)) {
          course.mark_completed(year_term, degree_plan);
        }
      }
      ref1 = this.coreqs;
      for (k = 0, len1 = ref1.length; k < len1; k++) {
        course = ref1[k];
        if (!(course.completed && course.year_term_taken)) {
          course.mark_completed(year_term, degree_plan);
        }
      }
      ref2 = this.downstream(courses);
      // make sure that upstream courses know about the changes. You'd think
      // that refresh would handle this, but it seems it doesn't, at least in the
      // case where marking something complete would make its prerequsities be
      // complete, but then courses downstream from those prerequisites would NOT
      // get marked complete. This appears to fix the problem.
      results = [];
      for (l = 0, len2 = ref2.length; l < len2; l++) {
        course = ref2[l];
        results.push(course.refresh(year_term, year_term, degree_plan));
      }
      return results;
    }

    mark_enrolling(year_term, degree_plan) {
      this.completed = false;
      this.year_term_taken = year_term;
      this.enrolling = true;
      this.clear_formatting();
      if (degree_plan) {
        if (degree_plan.required(this)) {
          $(this.card_sel).addClass('border-thick');
          $(this.header_sel).addClass('font-weight-bold');
        }
      }
      $(this.card_sel).addClass('border-primary');
      $(this.header_sel).addClass('bg-primary text-white');
      $(this.completed_sel).prop('checked', false);
      $(this.enrolling_sel).prop('checked', true);
      $(this.completed_sel).prop('disabled', true);
      $(this.enrolling_sel).prop('disabled', false);
      return $(this.modal_sel).addClass('btn-primary');
    }

    refresh(old_year_term, new_year_term, degree_plan) {
      // moving to future year? convert class from enrolling to taken
      if (new_year_term.value() > old_year_term.value()) {
        if (this.enrolling) {
          this.mark_completed(old_year_term, degree_plan);
          $(this.enrolling_sel).prop('checked', this.enrolling);
          return $(this.completed_sel).prop('checked', this.completed);
        } else if (this.completed) {
          if (new_year_term.value() > this.year_term_taken.value()) {
            return this.mark_completed(this.year_term_taken, degree_plan);
          }
        } else if (this.available(new_year_term)) {
          return this.mark_available(degree_plan);
        } else {
          return this.mark_unavailable(degree_plan);
        }
      
      // staying in the same year-term (changed status of one course)
      } else if (new_year_term.value() === old_year_term.value()) {
        if (this.completed) {
          if (!this.year_term_taken) {
            // probably just marked completed; pretend it was taken the term
            // before it was marked completed
            return this.mark_completed(old_year_term.prev(), degree_plan);
          } else {
            return this.mark_completed(this.year_term_taken, degree_plan);
          }
        } else if (this.enrolling) {
          return this.mark_enrolling(new_year_term, degree_plan);
        } else if (this.available(new_year_term)) {
          return this.mark_available(degree_plan);
        } else {
          return this.mark_unavailable(degree_plan);
        }
      } else {
        // going back in time; might need to unset date taken
        if (this.completed) {
          if (new_year_term.value() > this.year_term_taken.value()) {
            return this.mark_completed(this.year_term_taken, degree_plan);
          } else if (new_year_term.value() === this.year_term_taken.value()) {
            return this.mark_enrolling(this.year_term_taken, degree_plan);
          } else if (this.available(new_year_term)) {
            return this.mark_available(degree_plan);
          } else {
            return this.mark_unavailable(degree_plan);
          }
        // not completed, but it was marked enrolling? Then it isn't taken or
        // enrolled. Pretend it it never happened
        } else if (this.available(new_year_term)) {
          return this.mark_available(degree_plan);
        } else {
          return this.mark_unavailable(degree_plan);
        }
      }
    }

  };

  DegreePlan = class DegreePlan {
    constructor(degree_plan_info) {
      var class_name, combo, j, k, l, len, len1, len2, len3, len4, len5, len6, len7, len8, m, n, new_combo, new_sequence, o, p, q, r, ref, ref1, ref2, ref3, ref4, sequence;
      this.degree_plan_info = degree_plan_info;
      this.name = this.degree_plan_info.name;
      this.credits_needed = this.degree_plan_info.credits_needed;
      this.counted_classes = {
        requirements: [],
        choices: []
      };
      this.uncounted_classes = {
        requirements: [],
        choices: []
      };
      this.extra_electives = [];
      this.course_groups = this.degree_plan_info.course_groups;
      // track class objects in the various requirements, rather than just class
      // designations
      if (this.degree_plan_info.counted !== void 0) {
        if (this.degree_plan_info.counted.requirements !== void 0) {
          ref = this.degree_plan_info.counted.requirements;
          for (j = 0, len = ref.length; j < len; j++) {
            class_name = ref[j];
            this.counted_classes.requirements.push(get_course(class_name));
          }
        }
        if (this.degree_plan_info.counted.choices !== void 0) {
          ref1 = this.degree_plan_info.counted.choices;
          for (k = 0, len1 = ref1.length; k < len1; k++) {
            combo = ref1[k];
            new_combo = [];
            for (l = 0, len2 = combo.length; l < len2; l++) {
              sequence = combo[l];
              new_sequence = [];
              for (m = 0, len3 = sequence.length; m < len3; m++) {
                class_name = sequence[m];
                new_sequence.push(get_course(class_name));
              }
              new_combo.push(new_sequence);
            }
            this.counted_classes.choices.push(new_combo);
          }
        }
      }
      if (this.degree_plan_info.uncounted !== void 0) {
        if (this.degree_plan_info.uncounted.requirements !== void 0) {
          ref2 = this.degree_plan_info.uncounted.requirements;
          for (n = 0, len4 = ref2.length; n < len4; n++) {
            class_name = ref2[n];
            this.uncounted_classes.requirements.push(get_course(class_name));
          }
        }
        if (this.degree_plan_info.uncounted.choices !== void 0) {
          ref3 = this.degree_plan_info.uncounted.choices;
          for (o = 0, len5 = ref3.length; o < len5; o++) {
            combo = ref3[o];
            new_combo = [];
            for (p = 0, len6 = combo.length; p < len6; p++) {
              sequence = combo[p];
              new_sequence = [];
              for (q = 0, len7 = sequence.length; q < len7; q++) {
                class_name = sequence[q];
                new_sequence.push(get_course(class_name));
              }
              new_combo.push(new_sequence);
            }
            this.uncounted_classes.choices.push(new_combo);
          }
        }
      }
      if (this.degree_plan_info.extra_electives !== void 0) {
        ref4 = this.degree_plan_info.extra_electives;
        for (r = 0, len8 = ref4.length; r < len8; r++) {
          class_name = ref4[r];
          this.extra_electives.push(get_course(class_name));
        }
      }
    }

    // determine if a course sequence (part of a combination of possible options)
    // is "complete". It's considered complete when all courses are already
    // completed OR ENROLLED (which may be counterintuitive, but this lets us
    // mark other sequences as not required anymore)
    sequence_completed(sequence) {
      var course, j, len, res;
      res = true;
      for (j = 0, len = sequence.length; j < len; j++) {
        course = sequence[j];
        res = res && (course.completed || course.enrolling);
      }
      return res;
    }

    // determine if a course is "required". We interpret this to be if the class
    // is simply a required course, or it is part of a sequence of courses
    // comprising one possibility in a combination option. Note that partially-
    // completed sequences will still courses in OTHER sequences in the same combo
    // to appear as required.
    required(course) {
      var combo, j, k, l, len, len1, len2, len3, m, ref, ref1, sequence;
      // first check required courses (simple)
      if (this.counted_classes.requirements.includes(course)) {
        return true;
      } else if (this.uncounted_classes.requirements.includes(course)) {
        return true;
      } else if (!(this.counted_classes.choices.flat(4).includes(course) || this.uncounted_classes.choices.flat(4).includes(course))) {
        return false;
      // Crap. It's a class in a series of choices, so we need to figure out
      // if another option has already been completed.
      } else if (this.counted_classes.choices.flat(4).includes(course)) {
        ref = this.counted_classes.choices;
        // each "combo" is really a collection of course sequences (each of which
        // may only contain one course). The points is there could be a
        // requirement to take one of classes A, B, and C, AND there could be
        // an additional requirement that someone take both D and E, or just F.
        // In this example, [A], [B], and [C] represent a combination of
        // sequences, each of length 1.
        for (j = 0, len = ref.length; j < len; j++) {
          combo = ref[j];
          // don't consider combination of sequences if course doesn't appear
          if (!combo.flat(3).includes(course)) {
            continue;
          }
// bail out if any one sequence is completed; this class isn't needed
          for (k = 0, len1 = combo.length; k < len1; k++) {
            sequence = combo[k];
            // skip the sequence if the class appears in it (it might be complete,
            // but our convention is that completed courses can still be
            // "required")
            if (sequence.flat(2).includes(course)) {
              continue;
            }
            if (this.sequence_completed(sequence)) {
              return false;
            }
          }
        }
        return true;
      } else if (this.uncounted_classes.choices.flat(4).includes(course)) {
        ref1 = this.uncounted_classes.choices;
        for (l = 0, len2 = ref1.length; l < len2; l++) {
          combo = ref1[l];
          // don't consider combination of sequences if course doesn't appear
          if (!combo.flat(3).includes(course)) {
            continue;
          }
// bail out if any one sequence is completed
          for (m = 0, len3 = combo.length; m < len3; m++) {
            sequence = combo[m];
            // skip the sequence if the class appears in it (it might be complete,
            // but our convention is that completed courses can still be
            // "required")
            if (sequence.flat(2).includes(course)) {
              continue;
            }
            if (this.sequence_completed(sequence)) {
              return false;
            }
          }
        }
        return true;
      }
    }

    // compute how many credits count towards the degree requirement
    credit_count() {
      var course, credit_count, j, len;
      credit_count = 0;
      for (j = 0, len = courses.length; j < len; j++) {
        course = courses[j];
        if (course.completed || course.enrolling) {
          // is course explicitly a requirement, choice, or explicit elective?
          if (this.counted_classes.requirements.includes(course) || this.counted_classes.choices.flat(3).includes(course) || this.extra_electives.includes(course)) {
            credit_count += course.credits;
          // is course an implicit elective (PHYS class numbered over 325)
          } else if (course.field === 'PHYS' && course.number > 325) {
            credit_count += course.credits;
          }
        }
      }
      return credit_count;
    }

  };

  YearTerm = class YearTerm {
    constructor(year1, term1) {
      this.year = year1;
      this.term = term1;
    }

    value() {
      var res;
      res = this.year * 10;
      if (this.term === 'fall') {
        res += 5;
      }
      return res;
    }

    prev() {
      var new_term, new_year;
      new_term = 'fall';
      new_year = this.year;
      if (this.term === 'fall') {
        new_term = 'spring';
      } else {
        new_year -= 1;
      }
      return new YearTerm(new_year, new_term);
    }

    next() {
      var new_term, new_year;
      new_term = 'fall';
      new_year = this.year;
      if (this.term === 'fall') {
        new_term = 'spring';
        new_year += 1;
      }
      return new YearTerm(new_year, new_term);
    }

    toString() {
      return `${this.term.replace(/^\w/, (c) => {
        return c.toUpperCase();
      })} ${this.year}`;
    }

  };

  
  // combine course data with the course class to make useful objects
  MATH_112 = new Course(course_data.MATH_112);

  MATH_114 = new Course(course_data.MATH_114);

  MATH_215 = new Course(course_data.MATH_215);

  MATH_216 = new Course(course_data.MATH_216);

  MATH_312 = new Course(course_data.MATH_312);

  MATH_345 = new Course(course_data.MATH_345);

  CHEM_105 = new Course(course_data.CHEM_105);

  CHEM_106 = new Course(course_data.CHEM_106);

  CHEM_109 = new Course(course_data.CHEM_109);

  CHEM_115 = new Course(course_data.CHEM_115);

  MSE_120 = new Course(course_data.MSE_120);

  MSE_221 = new Course(course_data.MSE_221);

  MSE_350 = new Course(course_data.MSE_350);

  MSE_374 = new Course(course_data.MSE_374);

  MSE_315 = new Course(course_data.MSE_315);

  MSE_357 = new Course(course_data.MSE_357);

  MSE_372 = new Course(course_data.MSE_372);

  MSE_451 = new Course(course_data.MSE_451);

  PHYS_115 = new Course(course_data.PHYS_115);

  PHYS_186 = new Course(course_data.PHYS_186);

  PHYS_205 = new Course(course_data.PHYS_205);

  PHYS_226 = new Course(course_data.PHYS_226);

  PHYS_229 = new Course(course_data.PHYS_229);

  PHYS_231 = new Course(course_data.PHYS_231);

  PHYS_232 = new Course(course_data.PHYS_232);

  PHYS_240 = new Course(course_data.PHYS_240);

  PHYS_255 = new Course(course_data.PHYS_255);

  PHYS_308 = new Course(course_data.PHYS_308);

  PHYS_315 = new Course(course_data.PHYS_315);

  PHYS_332 = new Course(course_data.PHYS_332);

  PHYS_333 = new Course(course_data.PHYS_333);

  PHYS_340 = new Course(course_data.PHYS_340);

  PHYS_350 = new Course(course_data.PHYS_350);

  PHYS_356 = new Course(course_data.PHYS_356);

  PHYS_360 = new Course(course_data.PHYS_360);

  PHYS_361 = new Course(course_data.PHYS_361);

  PHYS_362 = new Course(course_data.PHYS_362);

  PHYS_363 = new Course(course_data.PHYS_363);

  PHYS_365 = new Course(course_data.PHYS_365);

  PHYS_367 = new Course(course_data.PHYS_367);

  PHYS_375 = new Course(course_data.PHYS_375);

  PHYS_430 = new Course(course_data.PHYS_430);

  PHYS_445 = new Course(course_data.PHYS_445);

  PHYS_465 = new Course(course_data.PHYS_465);

  PHYS_486 = new Course(course_data.PHYS_486);

  /* IMPORTANT GLOBAL VARIABLE */
  // This lists all the coures objects and is used in several classes, which
  // is terrible form, but hey, it works! Well, usually... The order is important.
  // When cycling through the courses, its best if prerequisites come before
  // the courses they depend on. So math courses should always go first, and then
  // mostly courses can simply increase in number. However, care must be taken to
  // ensure that some MSE courses are in the right place. For instance, MSE 451
  // depends on PHYS 333, but if it comes before PHYS 333, completing PHYS 333
  // will not immediately cause PHYS 451 to be marked as available because it is
  // refreshed *before* PHYS 333 since it's earlier on the list.

  // Fall 2022: Removed PHYS 205, 361, 362, and 363
  courses = [MATH_112, MATH_114, MATH_215, MATH_216, MATH_312, MATH_345, CHEM_105, CHEM_106, CHEM_109, CHEM_115, PHYS_115, PHYS_186, PHYS_226, PHYS_229, PHYS_231, PHYS_232, PHYS_240, PHYS_255, PHYS_308, PHYS_315, PHYS_332, PHYS_333, PHYS_340, PHYS_350, PHYS_356, PHYS_360, PHYS_365, PHYS_367, PHYS_375, PHYS_430, PHYS_445, PHYS_465, PHYS_486, MSE_120, MSE_315, MSE_221, MSE_350, MSE_357, MSE_372, MSE_374, MSE_451];

// firm up requirements so they work properly
  for (j = 0, len = courses.length; j < len; j++) {
    course = courses[j];
    course.update_requirements(courses);
  }

  // Fall 2022: Removed PHYS 205, 361, 362, and 363, which were electives or required
  // courses in each degree plan. PHYS 205 was a "basic elective" for the minor
  // and appeared nowhere else
  degree_plan_data = [
    {
      name: 'Liberal Arts',
      credits_needed: 36,
      counted: {
        requirements: ['PHYS 186',
    'PHYS 231',
    'PHYS 232',
    'PHYS 332',
    'PHYS 333',
    'PHYS 350',
    'PHYS 365',
    'PHYS 486'],
        choices: [[['PHYS 340'],
    ['PHYS 360']]]
      },
      uncounted: {
        requirements: ['MATH 312',
    'PHYS 240'],
        choices: []
      },
      extra_electives: ['MSE 374',
    'MSE 357',
    'MSE 372',
    'MSE 451'],
      course_groups: [
        {
          title: 'Introductory and Prerequisite Courses',
          courses: [MATH_112,
        MATH_114,
        MATH_215,
        MATH_216,
        PHYS_186,
        PHYS_231,
        PHYS_232,
        PHYS_240]
        },
        {
          title: 'Intermediate Courses',
          courses: [MATH_312,
        PHYS_332,
        PHYS_333,
        PHYS_340,
        PHYS_350,
        PHYS_365]
        },
        {
          title: 'Advanced Courses',
          courses: [PHYS_360,
        PHYS_486]
        },
        {
          title: 'Electives',
          courses: [PHYS_367,
        PHYS_375,
        PHYS_430,
        PHYS_445,
        PHYS_465,
        MSE_315,
        MSE_357,
        MSE_372,
        MSE_374,
        MSE_451]
        },
        {
          title: 'Elective Support (uncounted towards major)',
          courses: [CHEM_105,
        CHEM_106,
        CHEM_109,
        CHEM_115,
        MSE_221,
        MSE_350]
        }
      ]
    },
    {
      name: 'Applied',
      credits_needed: 36,
      counted: {
        requirements: ['PHYS 231',
    'PHYS 232',
    'PHYS 332',
    'PHYS 340',
    'PHYS 350',
    'PHYS 360',
    'PHYS 430',
    'PHYS 486'],
        choices: [[['PHYS 186'],
    ['MSE 120']],
    [['PHYS 255',
    'PHYS 356'],
    ['PHYS 365'],
    ['PHYS 375']]]
      },
      uncounted: {
        requirements: ['MATH 312',
    'MATH 345',
    'PHYS 240'],
        choices: [[['CHEM 115'],
    ['CHEM 105',
    'CHEM 106',
    'CHEM 109']]]
      },
      extra_electives: ['MSE 374',
    'MSE 357',
    'MSE 372',
    'MSE 451'],
      course_groups: [
        {
          title: 'Introductory and Prerequisite Courses',
          courses: [MATH_112,
        MATH_114,
        MATH_215,
        MATH_216,
        PHYS_186,
        MSE_120,
        PHYS_231,
        PHYS_232,
        PHYS_240,
        CHEM_105,
        CHEM_106,
        CHEM_109,
        CHEM_115]
        },
        {
          title: 'Intermediate Courses',
          courses: [MATH_312,
        MATH_345,
        PHYS_255,
        PHYS_332,
        PHYS_340,
        PHYS_350,
        PHYS_365]
        },
        {
          title: 'Advanced Courses',
          courses: [PHYS_356,
        PHYS_360,
        PHYS_375,
        PHYS_430,
        PHYS_486]
        },
        {
          title: 'Electives',
          courses: [PHYS_333,
        PHYS_367,
        PHYS_445,
        PHYS_465,
        MSE_315,
        MSE_357,
        MSE_372,
        MSE_374,
        MSE_451]
        },
        {
          title: 'Elective Support (uncounted towards major)',
          courses: [MSE_221,
        MSE_350]
        }
      ]
    },
    {
      name: 'Astrophysics',
      credits_needed: 36,
      counted: {
        requirements: ['PHYS 186',
    'PHYS 231',
    'PHYS 232',
    'PHYS 332',
    'PHYS 333',
    'PHYS 340',
    'PHYS 365',
    'PHYS 367',
    'PHYS 430',
    'PHYS 486'],
        choices: [[['PHYS 226'],
    ['PHYS 229']],
    [['PHYS 375'],
    ['PHYS 445'],
    ['PHYS 465']]]
      },
      uncounted: {
        requirements: ['MATH 312',
    'PHYS 240'],
        choices: []
      },
      extra_electives: [],
      course_groups: [
        {
          title: 'Introductory and Prerequisite Courses',
          courses: [MATH_112,
        MATH_114,
        MATH_215,
        MATH_216,
        PHYS_186,
        PHYS_226,
        PHYS_229,
        PHYS_231,
        PHYS_232,
        PHYS_240]
        },
        {
          title: 'Intermediate Courses',
          courses: [MATH_312,
        PHYS_332,
        PHYS_333,
        PHYS_340,
        PHYS_367]
        },
        {
          title: 'Advanced Courses',
          courses: [PHYS_365,
        PHYS_375,
        PHYS_430,
        PHYS_445,
        PHYS_465,
        PHYS_486]
        },
        {
          title: 'Electives (not needed for credit towards major)',
          courses: [PHYS_350,
        PHYS_360]
        }
      ]
    },
    {
      name: 'Dual Degree',
      credits_needed: 36,
      counted: {
        requirements: ['MSE 120',
    'PHYS 231',
    'PHYS 232',
    'PHYS 332',
    'PHYS 340',
    'PHYS 350'],
        choices: [[['PHYS 255',
    'PHYS 356'],
    ['PHYS 365']]]
      },
      uncounted: {
        requirements: ['MATH 312',
    'PHYS 240'],
        choices: []
      },
      extra_electives: ['MSE 374',
    'MSE 357',
    'MSE 372',
    'MSE 451'],
      course_groups: [
        {
          title: 'Introductory and Prerequisite Courses',
          courses: [MATH_112,
        MATH_114,
        MATH_215,
        MATH_216,
        MSE_120,
        PHYS_231,
        PHYS_232,
        PHYS_240]
        },
        {
          title: 'Intermediate Courses',
          courses: [MATH_312,
        PHYS_255,
        PHYS_332,
        PHYS_340,
        PHYS_350,
        PHYS_365]
        },
        {
          title: 'Advanced Courses',
          courses: [PHYS_356]
        },
        {
          title: 'Electives',
          courses: [PHYS_333,
        PHYS_360,
        PHYS_367,
        PHYS_375,
        PHYS_430,
        PHYS_445,
        PHYS_465,
        MSE_374,
        MSE_357,
        MSE_372,
        MSE_451]
        },
        {
          title: 'Elective Support (uncounted towards major)',
          courses: [CHEM_105,
        CHEM_106,
        CHEM_109,
        CHEM_115,
        MSE_221,
        MSE_350]
        }
      ]
    },
    {
      name: 'Minor',
      credits_needed: 24,
      counted: {
        requirements: ['PHYS 231',
    'PHYS 232',
    'PHYS 332'],
        choices: []
      },
      uncounted: {
        requirements: ['MATH 215'],
        choices: []
      },
      extra_electives: ['PHYS 115',
    'PHYS 186',
    'PHYS 205',
    'PHYS 226',
    'PHYS 229',
    'PHYS 240',
    'PHYS 308',
    'PHYS 315'],
      course_groups: [
        {
          title: 'Prerequisite Courses',
          courses: [MATH_112,
        MATH_114,
        MATH_215]
        },
        {
          title: 'Required Courses',
          courses: [PHYS_231,
        PHYS_232,
        PHYS_332]
        },
        {
          title: 'Basic Electives',
          courses: [PHYS_115,
        PHYS_186,
        PHYS_226,
        PHYS_229,
        PHYS_240,
        PHYS_308,
        PHYS_315]
        },
        {
          title: 'Advanced Electives',
          courses: [PHYS_333,
        PHYS_340,
        PHYS_350,
        PHYS_356,
        PHYS_360,
        PHYS_365,
        PHYS_367,
        PHYS_375,
        PHYS_430,
        PHYS_445,
        PHYS_465,
        PHYS_486]
        }
      ]
    }
  ];

  // obsolete_degree_plans = [
  //   {
  //     name: 'LabVIEW'
  //     credits_needed: 13
  //     counted:
  //       requirements: ['PHYS 350', 'PHYS 360', 'PHYS 361', 'PHYS 362', 'PHYS 363']
  //       choices: []
  //     uncounted:
  //       requirements: []
  //       choices: []
  //     course_groups: [
  //       {
  //         title: 'Introductory and Prerequisite Courses'
  //         courses: [MATH_112, MATH_114, MATH_215, PHYS_231, PHYS_232, PHYS_240]
  //       },
  //       {
  //         title: 'Certificate Courses'
  //         courses: [PHYS_350, PHYS_360, PHYS_361, PHYS_362, PHYS_363]
  //       },
  //     ]
  //   }
  // ]
  get_course = function(designation) {
    var field, k, len1, number;
    field = designation.split(' ')[0];
    number = Number(designation.split(' ')[1]);
    for (k = 0, len1 = courses.length; k < len1; k++) {
      course = courses[k];
      if (course.field === field && course.number === number) {
        return course;
      }
    }
  };

  // set up degree plans
  degree_plans = degree_plan_data.map(function(dpd) {
    return new DegreePlan(dpd);
  });

  get_degree_plan = function(plan_name) {
    var dp, k, len1;
    for (k = 0, len1 = degree_plans.length; k < len1; k++) {
      dp = degree_plans[k];
      if (dp.name === plan_name) {
        return dp;
      }
    }
  };

  // compute counted credits towards the degree
  today = new Date();

  current_year = today.getFullYear();

  current_month = today.getMonth();

  first_term = 'fall';

  second_term = 'spring';

  year_terms = [new YearTerm(current_year, 'spring'), new YearTerm(current_year, 'fall'), new YearTerm(current_year + 1, 'spring'), new YearTerm(current_year + 1, 'fall'), new YearTerm(current_year + 2, 'spring'), new YearTerm(current_year + 2, 'fall'), new YearTerm(current_year + 3, 'spring'), new YearTerm(current_year + 3, 'fall'), new YearTerm(current_year + 4, 'spring'), new YearTerm(current_year + 4, 'fall'), new YearTerm(current_year + 5, 'spring'), new YearTerm(current_year + 5, 'fall'), new YearTerm(current_year + 6, 'spring')];

  if (current_month < 5) {
    year_terms = year_terms.slice(0, 12);
  } else {
    year_terms = year_terms.slice(1, 13);
  }

  // Fall 2022: Removed PHYS 361, PHYS 362, and PHYS 363, which were "Intermediate
  // Courses". Actually, only PHYS 361 was. PHYS 362 and PHYS 363 didn't appear.
  wizard = {
    year_term: year_terms[0],
    degree_plan: degree_plans[0],
    course_groups: [
      {
        title: 'Introductory and Prerequisite Courses',
        courses: [MATH_112,
      MATH_114,
      MATH_215,
      MATH_216,
      PHYS_186,
      PHYS_231,
      PHYS_232,
      PHYS_240]
      },
      {
        title: 'Intermediate Courses',
        courses: [MATH_312,
      PHYS_255,
      PHYS_332,
      PHYS_333,
      PHYS_340,
      PHYS_350,
      PHYS_365]
      },
      {
        title: 'Advanced Courses',
        courses: [PHYS_356,
      PHYS_360,
      PHYS_367,
      PHYS_375,
      PHYS_430,
      PHYS_445,
      PHYS_465,
      PHYS_486]
      },
      {
        title: 'Other Courses',
        courses: [CHEM_105,
      CHEM_106,
      CHEM_109,
      CHEM_115,
      MATH_345]
      }
    ],
    clear_groups: function() {
      return $('#body').html('');
    },
    add_group: function(new_group) {
      var k, len1, ref, to_add;
      to_add = "<hr class='my-4'>\n";
      to_add += "<div class='row'><div class='col'>\n";
      to_add += `  <h2>${new_group.title}</h2>\n`;
      to_add += "</div></div>\n";
      to_add += "<div class='row'>\n";
      ref = new_group.courses;
      for (k = 0, len1 = ref.length; k < len1; k++) {
        course = ref[k];
        to_add += "  <div class='col-12 col-md-6 col-lg-4 col-xl-3 mb-3'>\n";
        to_add += `    ${course.html_card}`;
        to_add += "  </div>\n";
      }
      to_add += "</div>\n";
      return $('#body').append(to_add);
    },
    refresh: function(old_year_term) {
      var credit_count, k, len1;
      for (k = 0, len1 = courses.length; k < len1; k++) {
        course = courses[k];
        course.refresh(old_year_term, wizard.year_term, wizard.degree_plan);
      }
      // update credit count display
      credit_count = wizard.degree_plan.credit_count();
      $('#credit_count').html(credit_count);
      if (credit_count >= wizard.degree_plan.credits_needed) {
        $('#credit-status').removeClass('text-danger').addClass('text-success');
      } else {
        $('#credit-status').addClass('text-danger').removeClass('text-success');
      }
      // update the course plan
      return wizard.build_course_plan();
    },
    set_degree_plan: function(new_degree_plan) {
      var group, k, len1, ref;
      wizard.degree_plan = new_degree_plan;
      wizard.clear_groups();
      ref = wizard.degree_plan.course_groups;
      for (k = 0, len1 = ref.length; k < len1; k++) {
        group = ref[k];
        wizard.add_group(group);
      }
      $('#credits-needed').html(`${new_degree_plan.credits_needed}`);
      return wizard.setup_course_listeners();
    },
    build_course_plan: function() {
      var k, l, len1, len2, len3, m, table_html, this_year_term_courses, year_term;
      $('#course-plan').html('');
      table_html = "";
      for (k = 0, len1 = year_terms.length; k < len1; k++) {
        year_term = year_terms[k];
        this_year_term_courses = [];
        for (l = 0, len2 = courses.length; l < len2; l++) {
          course = courses[l];
          if (course.completed || course.enrolling) {
            if (course.year_term_taken.value() === year_term.value()) {
              this_year_term_courses.push(course);
            }
          }
        }
        if (this_year_term_courses.length > 0) {
          table_html += "  <thead class='thead-dark'>\n";
          table_html += `    <tr><th scope='col' colspan=3 class='text-center'>${year_term}</th></tr>\n`;
          table_html += "  </thead>\n";
          table_html += "  <thead class='thead-light'>\n";
          table_html += "    <tr>\n";
          table_html += "      <th scope='col'>Course #</th>\n";
          table_html += "      <th scope='col'>Course Name</th>\n";
          table_html += "      <th scope='col'>Credits</th>\n";
          table_html += "    </tr>\n";
          table_html += "  </thead>\n";
          table_html += "  <tbody>\n";
          for (m = 0, len3 = this_year_term_courses.length; m < len3; m++) {
            course = this_year_term_courses[m];
            table_html += "    <tr>\n";
            table_html += `      <td>${course.field} ${course.number}</td>\n`;
            table_html += `      <td>${course.name}</td>\n`;
            table_html += `      <td>${course.credits}</td>\n`;
            table_html += "    </tr>\n";
          }
          table_html += "  </tbody>\n";
        }
      }
      if (table_html !== "") {
        table_html = `<table class='table table-hover table-sm'>\n${table_html}</table>\n`;
        return $('#course-plan').html(`<h1 class='my-4'>Course Plan</h1>\n${table_html}`);
      }
    },
    setup_course_listeners: function() {
      // activate switch listeners
      $('input.completed').click(function() {
        var this_course;
        this_course = get_course(this.id.split('-').slice(0, 2).join(' '));
        this_course.toggle_completed();
        return wizard.refresh(wizard.year_term);
      });
      $('input.enrolling').click(function() {
        get_course(this.id.split('-').slice(0, 2).join(' ')).toggle_enrolling();
        return wizard.refresh(wizard.year_term);
      });
      // activate modal description listeners
      return $('button.description').click(function() {
        course = get_course(this.id.split('-').slice(0, 2).join(' '));
        course.update_modal(wizard.year_term);
        $('#course-info').modal();
        $('#modal-enrolling').click(function(event) {
          event.preventDefault;
          // leverage the fact that the title has the course name in it, with a
          // colon right after it. Janky, but it works for now!
          course = get_course($('#course-info-label').text().split(':')[0]);
          course.enrolling = true;
          course.completed = false;
          // for i in [0...5]
          wizard.refresh(wizard.year_term);
          return $('#course-info').modal('hide');
        });
        return $('#modal-completed').click(function(event) {
          event.preventDefault;
          // leverage the fact that the title has the course name in it, with a
          // colon right after it. Janky, but it works for now!
          course = get_course($('#course-info-label').text().split(':')[0]);
          course.enrolling = false;
          course.completed = true;
          wizard.refresh(wizard.year_term);
          return $('#course-info').modal('hide');
        });
      });
    },
    setup: function() {
      /* Year Term Menu and Next Button */
      var dp, first_year, i, k, l, len1, term, year;
      first_year = year_terms[0].year;
      first_term = year_terms[0].term.replace(/^\w/, (c) => {
        return c.toUpperCase();
      });
      // populate dropdown menu
      $('#year-term-dropdown').text(`${first_term} ${first_year}`);
      for (i = k = 0; k <= 11; i = ++k) {
        year = year_terms[i].year;
        term = year_terms[i].term.replace(/^\w/, (c) => {
          return c.toUpperCase();
        });
        $(`#year-term-menu>a[data-position='${i}']`).text(`${term} ${year}`);
      }
      // Set up listeners for year-term dropdown menu
      $('#year-term-menu>a').click(function(event) {
        var new_term, old_year_term, position;
        event.preventDefault();
        // update year-term, but hold on to old one so we can refresh, which 
        // requires knowing both the old and new term
        old_year_term = wizard.year_term;
        position = Number($(this).data('position'));
        wizard.year_term = year_terms[position];
        // move active status to new choice
        $('#year-term-menu>a').removeClass('active');
        $(`#year-term-menu>a[data-position='${position}']`).addClass('active');
        // update button text
        new_term = wizard.year_term.term.replace(/^\w/, (c) => {
          return c.toUpperCase();
        });
        $('#year-term-dropdown').text(`${new_term} ${wizard.year_term.year}`);
        wizard.refresh(old_year_term);
        // conditionally disable next button text
        if (wizard.year_term.value() === year_terms[year_terms.length - 1].value()) {
          return $('#next-term').prop('disabled', true);
        }
      });
      // get next term button working
      $('#next-term').click(function(event) {
        var new_term, old_year_term;
        event.preventDefault();
        // update year-term, but hold on to old one so we can refresh, which 
        // requires knowing both the old and new term
        old_year_term = wizard.year_term;
        wizard.year_term = wizard.year_term.next();
        new_term = wizard.year_term.term.replace(/^\w/, (c) => {
          return c.toUpperCase();
        });
        // move active status to new choice
        $('#year-term-menu>a').removeClass('active');
        $(`#year-term-menu>a:contains('${new_term} ${wizard.year_term.year}')`).addClass('active');
        
        // update button text
        new_term = wizard.year_term.term.replace(/^\w/, (c) => {
          return c.toUpperCase();
        });
        $('#year-term-dropdown').text(`${new_term} ${wizard.year_term.year}`);
        wizard.refresh(old_year_term);
        // conditionally disable next button
        if (wizard.year_term.value() === year_terms[year_terms.length - 1].value()) {
          return $('#next-term').prop('disabled', true);
        }
      });
      /* Degree Plan Dropdown */
      // initialize degree plan dropdown button text
      $('#degree-plan-dropdown').text(wizard.degree_plan.name);
// Populate degree plan dropdown
      for (l = 0, len1 = degree_plans.length; l < len1; l++) {
        dp = degree_plans[l];
        if (dp === wizard.degree_plan) {
          $('#degree-plan-menu').append(`<a class='dropdown-item degree-plan-option active' href='#'>${dp.name}</a>`);
        } else {
          $('#degree-plan-menu').append(`<a class='dropdown-item degree-plan-option' href='#'>${dp.name}</a>`);
        }
      }
      // make degree plan dropdown actually switch degree plans
      $('#degree-plan-menu>a.degree-plan-option').click(function(event) {
        var self;
        event.preventDefault();
        self = this;
        wizard.set_degree_plan(get_degree_plan(self.text));
        $('#degree-plan-menu>a.degree-plan-option').removeClass('active');
        $(`#degree-plan-menu>a.degree-plan-option:contains(${wizard.degree_plan.name})`).addClass('active');
        $('#degree-plan-dropdown').html(wizard.degree_plan.name);
        return wizard.refresh(wizard.year_term);
      });
      /* Setup Initial Degree Plan */
      wizard.set_degree_plan(wizard.degree_plan);
      // set up initial availability
      return wizard.refresh(wizard.year_term);
    }
  };

  $(document).ready(function() {
    wizard.setup();
    // enable popovers  
    $('[data-toggle="popover"]').popover();
    $('.popover-dismiss').popover({
      trigger: 'focus'
    });
    return $('a#print-page').click(function(event) {
      event.preventDefault();
      window.print();
      return setTimeout("window.close()", 100);
    });
  });

}).call(this);
