// Generated by CoffeeScript 2.5.1
(function() {
  var Course, MATH_112, MATH_114, MATH_215, MATH_216, MATH_312, PHYS_186, PHYS_231, PHYS_232, PHYS_240, PHYS_255, PHYS_332, PHYS_333, PHYS_340, PHYS_350, PHYS_356, PHYS_360, PHYS_361, PHYS_362, PHYS_363, PHYS_365, PHYS_367, PHYS_375, PHYS_430, PHYS_445, PHYS_465, PHYS_486, YearTerm, course, course_data, courses, current_month, current_year, first_term, j, len, second_term, today, wizard, year_terms;

  course_data = {
    MATH_112: {
      field: 'MATH',
      number: 112,
      name: 'Precalculus Mathematics',
      lecture_hours: 4,
      lab_hours: 0,
      credits: 4,
      description: 'Prepares students to enter the Math 114, Math 215, Math 216 sequence. Includes absolute value; logarithmic, exponential, and trigonometric functions; inequalities; conic sections; complex numbers; and topics from theory of equations.',
      le: ['S2'],
      requirements: null,
      years_offered: 'all',
      terms_offered: 'all'
    },
    MATH_114: {
      field: 'MATH',
      number: 114,
      name: 'Calculus I',
      lecture_hours: 4,
      lab_hours: 0,
      credits: 4,
      description: 'Limits, theory, and application of the derivative; introduction to integration.',
      le: ['S2'],
      requirements: {
        prereqs: ['MATH 112']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    MATH_215: {
      field: 'MATH',
      number: 215,
      name: 'Calculus II',
      lecture_hours: 4,
      lab_hours: 0,
      credits: 4,
      description: "Applications and techniques of integration; improper integrals; sequences and series; power series and Taylor's formula.",
      le: ['S2'],
      requirements: {
        prereqs: ['MATH 114']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    MATH_216: {
      field: 'MATH',
      number: 216,
      name: 'Calculus III',
      lecture_hours: 4,
      lab_hours: 0,
      credits: 4,
      description: "Introduction to functions of several variables, including partial derivatives, multiple integrals, the calculus of vector-valued functions, and Green's Theorem, Stokes' Theorem, and the Divergence Theorem.",
      le: [],
      requirements: {
        prereqs: ['MATH 215']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    MATH_312: {
      field: 'MATH',
      number: 312,
      name: 'Differential Equations and Linear Algebra',
      lecture_hours: 4,
      lab_hours: 0,
      credits: 4,
      description: "Linear algebra: basis, dimension, matrix algebra, determinants, inverses, systems of linear equations, eigenvalues/eigenvectors. (Optional) matrices as linear transformations. Differential equations: first-order linear, separable; second-order linear with constant coefficients; higher order differential equations; first-order linear systems with constant coefficients; Laplace transforms; power series solutions. (Optional) Proof of Existence and Uniqueness Theorems.",
      le: [],
      requirements: {
        prereqs: ['MATH 215']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    PHYS_186: {
      field: 'PHYS',
      number: 186,
      name: 'Introductory Seminar',
      lecture_hours: 0.5,
      lab_hours: 0,
      credits: 0.5,
      description: "Students will explore avenues for obtaining an internship, discuss plans for participating in the required research project, attend the weekly Physics Seminar, develop academic plans, and participate in postgraduate planning.",
      le: [],
      requirements: null,
      years_offered: 'all',
      terms_offered: 'fall'
    },
    PHYS_231: {
      field: 'PHYS',
      number: 231,
      name: 'University Physics I',
      lecture_hours: 4,
      lab_hours: 2,
      credits: 5,
      description: "Physics for science and engineering students, including the study of mechanics, simple harmonic motion, and wave motion.",
      le: ['K1', 'K1L'],
      requirements: {
        coreqs: ['MATH 114']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    PHYS_232: {
      field: 'PHYS',
      number: 232,
      name: 'University Physics II',
      lecture_hours: 4,
      lab_hours: 2,
      credits: 5,
      description: "A continuation of Physics 231, including the study of electricity, magnetism, and optics.",
      le: ['K1', 'K1L'],
      requirements: {
        coreqs: ['MATH 215'],
        prereqs: ['PHYS 231']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    PHYS_240: {
      field: 'PHYS',
      number: 240,
      name: 'Computational Physics',
      lecture_hours: 2,
      lab_hours: 2,
      credits: 3,
      description: "An introduction to the use of computational tools for solving physical problems. Topics include an introduction to computing, visualization techniques, numerical integration, and numerical solutions to differential equations.",
      le: [],
      requirements: {
        prereqs: ['PHYS 231']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    PHYS_255: {
      field: 'PHYS',
      number: 255,
      name: 'Statics',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "Designed primarily for pre-engineering students. Includes static equilibrium of rigid bodies, centroids, analysis of structures, friction, and moments of inertia.",
      le: [],
      requirements: {
        prereqs: ['PHYS 231'],
        coreqs: ['MATH 215']
      },
      years_offered: 'all',
      terms_offered: 'fall'
    },
    PHYS_332: {
      field: 'PHYS',
      number: 332,
      name: 'University Physics III',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "Physics for science and engineering students, including the study of fluids, heat, thermodynamics, relativity, and an introduction to modern physics.",
      le: ['I1'],
      requirements: {
        prereqs: ['PHYS 232', 'MATH 215']
      },
      years_offered: 'all',
      terms_offered: 'all'
    },
    PHYS_333: {
      field: 'PHYS',
      number: 333,
      name: 'Quantum Physics',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "Introduction to the experimental and theoretical basis of quantum physics, including particle aspects of radiation, matter waves, Bohr model of the atom, Schrodinger wave mechanics and its application to the hydrogen atom and multi-electron atoms.",
      le: [],
      requirements: {
        prereqs: ['PHYS 332', 'MATH 216']
      },
      years_offered: 'even',
      terms_offered: 'fall'
    },
    PHYS_340: {
      field: 'PHYS',
      number: 340,
      name: 'Optics',
      lecture_hours: 3,
      lab_hours: 3,
      credits: 4,
      description: "Lecture and laboratory work cover geometrical and physical optics, image formation, optical instruments, interference, diffraction, polarization, and modern topics including lasers.",
      le: [],
      requirements: {
        prereqs: ['PHYS 232', 'MATH 215']
      },
      years_offered: 'all',
      terms_offered: 'spring'
    },
    PHYS_350: {
      field: 'PHYS',
      number: 350,
      name: 'Electric and Electronic Circuits',
      lecture_hours: 3,
      lab_hours: 3,
      credits: 4,
      description: "General introduction to electrical circuits and electronics including analysis of DC and AC circuits, simple passive filters, diodes, transistors, operational amplifiers, simple digital electronics, and circuit design and construction.",
      le: [],
      requirements: {
        prereqs: ['PHYS 232', 'MATH 215']
      },
      years_offered: 'all',
      terms_offered: 'fall'
    },
    PHYS_356: {
      field: 'PHYS',
      number: 356,
      name: 'Dynamics',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "A continuation of Physics 255. Dynamics of rigid bodies, moments of inertia, work, energy, impulse, and momentum.",
      le: [],
      requirements: {
        prereqs: ['PHYS 255', 'MATH 215'],
        exclude: ['PHYS 356']
      },
      years_offered: 'all',
      terms_offered: 'spring'
    },
    PHYS_360: {
      field: 'PHYS',
      number: 360,
      name: 'Electronics',
      lecture_hours: 3,
      lab_hours: 3,
      credits: 4,
      description: "Description, analysis, and laboratory measurements of digital and analog devices including transistor amplifiers, operational amplifiers, oscillators, gates, flip-flops, analog-digital converters, and microprocessors.",
      le: [],
      requirements: {
        prereqs: ['PHYS 350', 'MATH 240']
      },
      years_offered: 'all',
      terms_offered: 'spring'
    },
    PHYS_360: {
      field: 'PHYS',
      number: 360,
      name: 'Electronics',
      lecture_hours: 3,
      lab_hours: 3,
      credits: 4,
      description: "Description, analysis, and laboratory measurements of digital and analog devices including transistor amplifiers, operational amplifiers, oscillators, gates, flip-flops, analog-digital converters, and microprocessors.",
      le: [],
      requirements: {
        prereqs: ['PHYS 350', 'MATH 240']
      },
      years_offered: 'all',
      terms_offered: 'spring'
    },
    PHYS_361: {
      field: 'PHYS',
      number: 361,
      name: 'LabVIEW Basics',
      lecture_hours: 2,
      lab_hours: 0,
      credits: 2,
      description: "Lecture and laboratory work cover an introduction to the graphical programming language LabVIEW. LabVIEW has been widely adopted as the industry standard for computerized data acquisition, analysis and instrument control.",
      le: [],
      requirements: {
        coreqs: ['PHYS 350']
      },
      years_offered: 'all',
      terms_offered: 'fall'
    },
    PHYS_362: {
      field: 'PHYS',
      number: 362,
      name: 'LabVIEW Applications',
      lecture_hours: 2,
      lab_hours: 0,
      credits: 2,
      description: "Lecture and laboratory exercises cover applications using the graphical programming language LabVIEW. Topics include advanced programming structures, CompactDAQ hardware, digital signal processing, motor control, encoders, PID process control, RS-232 instrument control, component testing, sensor monitoring.",
      le: [],
      requirements: {
        prereqs: ['PHYS 361']
      },
      years_offered: 'all',
      terms_offered: 'spring'
    },
    PHYS_363: {
      field: 'PHYS',
      number: 363,
      name: 'LabVIEW cRIO',
      lecture_hours: 1,
      lab_hours: 0,
      credits: 1,
      description: "Lecture and laboratory exercises cover the theory and application of the cRIO automation controller using the graphical programming language LabVIEW. Topics include Real-Time operating system, field programmable gate array (FPGA) and network shared variables.",
      le: [],
      requirements: {
        coreqs: ['PHYS 362']
      },
      years_offered: 'all',
      terms_offered: 'spring'
    },
    PHYS_365: {
      field: 'PHYS',
      number: 365,
      name: 'Theoretical Mechanics',
      lecture_hours: 4,
      lab_hours: 0,
      credits: 4,
      description: "Newton's laws, accelerated frames, central-force orbits, angular momentum of systems, coupled oscillations, generalized coordinates, and Lagrange's equations.",
      le: [],
      requirements: {
        prereqs: ['MATH 216', 'PHYS 231', 'PHYS 240'],
        exclude: ['PHYS 356']
      },
      years_offered: 'all',
      terms_offered: 'fall'
    },
    PHYS_367: {
      field: 'PHYS',
      number: 367,
      name: 'Astrophysics',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "Physics applied to astronomical objects. The birth, structure, and evolution of stars are studied in detail. Nebulae, the interstellar medium, and stellar remnants are also investigated.",
      le: [],
      requirements: {
        prereqs: ['PHYS 240', 'PHYS 332']
      },
      years_offered: 'odd',
      terms_offered: 'fall'
    },
    PHYS_375: {
      field: 'PHYS',
      number: 375,
      name: 'Electromagnetic Fields',
      lecture_hours: 4,
      lab_hours: 0,
      credits: 4,
      description: "Electric and magnetic fields, dielectric and magnetic properties of materials, and electromagnetic phenomena. Field theory leading to the development of Maxwell's equations and the plane electromagnetic wave.",
      le: [],
      requirements: {
        prereqs: ['PHYS 240', 'PHYS 332', 'MATH 216', 'MATH 312']
      },
      years_offered: 'even',
      terms_offered: 'spring'
    },
    PHYS_430: {
      field: 'PHYS',
      number: 430,
      name: 'Advanced Laboratory Technique',
      lecture_hours: 0,
      lab_hours: 4,
      credits: 2,
      description: "Laboratory course for students with special interests in experimental physics. The emphasis is on widely applicable modern experimental methods.",
      le: [],
      requirements: {
        combo: {
          min: 2,
          options: ['PHYS 340', 'PHYS 350', 'PHYS 360']
        }
      },
      years_offered: 'all',
      terms_offered: 'fall'
    },
    PHYS_445: {
      field: 'PHYS',
      number: 445,
      name: 'Advanced Laboratory Technique',
      lecture_hours: 4,
      lab_hours: 0,
      credits: 4,
      description: "Statistical mechanics and thermodynamics including the laws of classical thermodynamics, equations of state, thermodynamical processes, and applications to classical and quantum mechanical systems.",
      le: [],
      requirements: {
        prereqs: ['PHYS 332', 'MATH 216']
      },
      years_offered: 'even',
      terms_offered: 'fall'
    },
    PHYS_465: {
      field: 'PHYS',
      number: 465,
      name: 'Quantum Mechanics',
      lecture_hours: 3,
      lab_hours: 0,
      credits: 3,
      description: "A continuation of Physics 333, including Dirac notation, operator methods, one dimensional potentials, spin and angular momentum, and the philosophical interpretation of quantum mechanics.",
      le: [],
      requirements: {
        prereqs: ['PHYS 333', 'MATH 312']
      },
      years_offered: 'odd',
      terms_offered: 'spring'
    },
    PHYS_486: {
      field: 'PHYS',
      number: 486,
      name: 'Introductory Seminar',
      lecture_hours: 0.5,
      lab_hours: 0,
      credits: 0.5,
      description: "Students will present a capstone project seminar, develop presentation skills (oral and poster), take a nationally normed test covering undergraduate physics, discuss their post-graduate plans, and assist the department in assessing the major.",
      le: ['S3 Creativity'],
      requirements: {
        custom: 'Students need to have completed an adviser-approved capstone project before entering this class. This can be accomplished through various means: PHYS 399, PHYS 430, PHYS 495, PHYS 499, through an academic or industrial internship, or through another approved means.'
      },
      years_offered: 'all',
      terms_offered: 'fall'
    }
  };

  Course = class Course {
    constructor(course_info) {
      this.course_info = course_info;
      // unpack course data object
      this.field = this.course_info.field;
      this.number = this.course_info.number;
      this.name = this.course_info.name;
      this.lecture_hours = this.course_info.lecture_hours;
      this.lab_hours = this.course_info.lab_hours;
      this.credits = this.course_info.credits;
      this.description = this.course_info.description;
      this.le = this.course_info.le;
      // designations are strings, regualar values hold actual courses
      // actual courses need to be set up later, since there's not guarantee 
      // the courses already exist, nor is there a way to get at them

      // prereqs: course must be taken BEFORE enrolling
      // coreqs: course must be taken BEFORE or WHILE enrolling
      // prereq_options: some number of these courses must be taken BEFORE enrolling
      // exclude: cannot enroll if any of these courses have been completed
      this.prereq_designations = [];
      this.coreq_designations = [];
      this.combo_option_designations = [];
      this.exclude_designations = [];
      this.prereqs = [];
      this.coreqs = [];
      this.combo_options = [];
      this.combo_option_min = 0;
      this.exclusions = [];
      if (this.course_info.requirements !== null) {
        if (this.course_info.requirements.prereqs !== void 0) {
          this.prereq_designations = this.course_info.requirements.prereqs;
        }
        if (this.course_info.requirements.coreqs !== void 0) {
          this.coreq_designations = this.course_info.requirements.coreqs;
        }
        if (this.course_info.requirements.combo !== void 0) {
          this.combo_option_designations = this.course_info.requirements.combo.options;
          this.combo_option_min = this.course_info.requirements.combo.min;
        }
        if (this.course_info.requirements.exclude !== void 0) {
          this.exclude_designations = this.course_info.requirements.exclude;
        }
      }
      this.years_offered = this.course_info.years_offered;
      this.terms_offered = this.course_info.terms_offered;
      // HTML helpers
      this.context_classes = ['default', 'primary', 'secondary', 'success', 'warning', 'danger'];
      this.all_border_classes = (this.context_classes.map(function(cls) {
        return 'border-' + cls;
      })).join(' ');
      this.all_bg_classes = (this.context_classes.map(function(cls) {
        return 'bg-' + cls;
      })).join(' ');
      this.all_btn_classes = (this.context_classes.map(function(cls) {
        return 'btn-' + cls;
      })).join(' ');
      // CSS IDs and Selectors
      this.completed_id = `${this.field}-${this.number}-completed`;
      this.enrolling_id = `${this.field}-${this.number}-enrolling`;
      this.card_id = `${this.field}${this.number}`;
      this.modal_id = `${this.field}-${this.number}`;
      this.completed_sel = '#' + this.completed_id;
      this.enrolling_sel = '#' + this.enrolling_id;
      this.card_sel = '#' + this.card_id;
      this.header_sel = this.card_sel + '>h5.card-header';
      this.modal_sel = '#' + this.modal_id;
      // state variables
      this.completed = false;
      this.enrolling = false;
      this.year_term_taken = false;
      // base HTML card
      this.html_card = `<div class='card' id='${this.card_id}'>\n`;
      this.html_card += `  <h5 class='card-header'>${this.field} ${this.number} <span class='font-italic'>(${this.credits} credits)</span></h5>\n`;
      this.html_card += "  <div class='card-body'>\n";
      this.html_card += `    <h5 class='card-title'>${this.name}</h5>\n`;
      // @html_card += "    <p class='card-text'>#{@description}</p>\n"
      this.html_card += "    <div class='row'>\n";
      this.html_card += "      <div class='col'>\n";
      this.html_card += `        <button type='button' class='btn btn-sm description' id='${this.modal_id}'>Details</button>\n`;
      this.html_card += "     </div>\n";
      this.html_card += "      <div class='col'>\n";
      this.html_card += "        <div class='custom-control custom-switch'>\n";
      this.html_card += `          <input type='checkbox' class='custom-control-input completed' id='${this.completed_id}'>\n`;
      this.html_card += `          <label for='${this.completed_id}' class='custom-control-label'>Completed</label>\n`;
      this.html_card += "        </div>\n";
      this.html_card += "        <div class='custom-control custom-switch'>\n";
      this.html_card += `          <input type='checkbox' class='custom-control-input enrolling' id='${this.enrolling_id}'>\n`;
      this.html_card += `          <label for='${this.enrolling_id}' class='custom-control-label'>Enrolling</label>\n`;
      this.html_card += "        </div>\n";
      this.html_card += "      </div>\n";
      this.html_card += "    </div>\n";
      this.html_card += "  </div>\n";
      this.html_card += "</div>";
    }

    toggle_completed() {
      return this.completed = !this.completed;
    }

    toggle_enrolling() {
      return this.enrolling = !this.enrolling;
    }

    update_modal(year_term) {
      var availability;
      $('#course-info-label').html(`${this.field} ${this.number}: ${this.name}`);
      $('#course-description').html('');
      $('#course-description').append(`<p>${this.description}</p>`);
      $('#course-description').append(`<p>Lecture Hours: ${this.lecture_hours}; Lab Hours: ${this.lab_hours}</p>`);
      if (this.prereq_designations.length > 0) {
        $('#course-description').append(`<p><span class='font-italic'>Prerequisites:</span> ${this.prereq_designations.join(', ')}</p>`);
      }
      if (this.coreq_designations.length > 0) {
        $('#course-description').append(`<p><span class='font-italic'>Corequisites:</span> ${this.coreq_designations.join(', ')}</p>`);
      }
      availability = 'Offered ';
      if (this.terms_offered === 'all') {
        availability += 'every term.';
      } else if (this.years_offered === 'all') {
        availability += `in the <span class='font-weight-bold'>${this.terms_offered} term</span> every year.`;
      } else {
        availability += `in the <span class='font-weight-bold'>${this.terms_offered} term of ${this.years_offered} years</span>.`;
      }
      $('#course-description').append(`<p>${availability}</p>`);
      return $('#modal-enrolling').prop('disabled', !this.available(year_term));
    }

    // update coreqs and prereqs from list of courses. Uses designations to 
    // query an array of courses, and then makes the actual course objects the
    // prerequisistes, corequisites, etc.
    update_requirements(courses) {
      var course, designation, j, k, l, len, len1, len2, len3, len4, len5, len6, m, n, o, p, ref, ref1, ref2, ref3, results;
      if (this.prereq_designations.length !== 0) {
        ref = this.prereq_designations;
        for (j = 0, len = ref.length; j < len; j++) {
          designation = ref[j];
          for (k = 0, len1 = courses.length; k < len1; k++) {
            course = courses[k];
            if (`${course.field} ${course.number}` === designation) {
              this.prereqs.push(course);
            }
          }
        }
      }
      ref1 = this.coreq_designations;
      for (l = 0, len2 = ref1.length; l < len2; l++) {
        designation = ref1[l];
        for (m = 0, len3 = courses.length; m < len3; m++) {
          course = courses[m];
          if (`${course.field} ${course.number}` === designation) {
            this.coreqs.push(course);
          }
        }
      }
      ref2 = this.combo_option_designations;
      for (n = 0, len4 = ref2.length; n < len4; n++) {
        designation = ref2[n];
        for (o = 0, len5 = courses.length; o < len5; o++) {
          course = courses[o];
          if (`${course.field} ${course.number}` === designation) {
            this.combo_options.push(course);
          }
        }
      }
      ref3 = this.exclude_designations;
      results = [];
      for (p = 0, len6 = ref3.length; p < len6; p++) {
        designation = ref3[p];
        results.push((function() {
          var len7, q, results1;
          results1 = [];
          for (q = 0, len7 = courses.length; q < len7; q++) {
            course = courses[q];
            if (`${course.field} ${course.number}` === designation) {
              results1.push(this.exclusions.push(course));
            } else {
              results1.push(void 0);
            }
          }
          return results1;
        }).call(this));
      }
      return results;
    }

    available(year_term) {
      var combo_count, combo_option, coreq, course, j, k, l, len, len1, len2, len3, m, prereq, ref, ref1, ref2, ref3, res, term, year;
      year = year_term.year;
      term = year_term.term;
      res = true;
      ref = this.prereqs;
      for (j = 0, len = ref.length; j < len; j++) {
        prereq = ref[j];
        res = res && prereq.completed;
      }
      ref1 = this.coreqs;
      for (k = 0, len1 = ref1.length; k < len1; k++) {
        coreq = ref1[k];
        res = res && (coreq.completed || coreq.enrolling);
      }
      // handle course with a minimum number of prerequisites from a collection
      // of courses
      combo_count = 0;
      ref2 = this.combo_options;
      for (l = 0, len2 = ref2.length; l < len2; l++) {
        combo_option = ref2[l];
        if (combo_option.completed) {
          combo_count += 1;
        }
      }
      res = res && (combo_count >= this.combo_option_min);
      ref3 = this.exclusions;
      // handle courses that exclude other courses (356 & 365)  
      for (m = 0, len3 = ref3.length; m < len3; m++) {
        course = ref3[m];
        res = res && !course.completed;
      }
      // offered this year?
      res = res && ((this.years_offered === 'all') || ((this.years_offered === 'even') && (year % 2 === 0)) || ((this.years_offered === 'odd') && (year % 2 === 1)));
      // offered this term?
      res = res && ((this.terms_offered === 'all') || this.terms_offered === year_term.term);
      return res;
    }

    clear_formatting() {
      $(this.card_sel).removeClass(this.all_border_classes);
      $(this.header_sel).removeClass(this.all_bg_classes);
      $(this.header_sel).removeClass('text-white');
      return $(this.modal_sel).removeClass(this.all_btn_classes);
    }

    // $(@modal_sel).addClass('btn-secondary')
    mark_available() {
      this.completed = false;
      this.year_term_taken = false;
      this.enrolling = false;
      this.clear_formatting();
      $(this.card_sel).addClass('border-warning');
      $(this.header_sel).addClass('bg-warning text-white');
      $(this.completed_sel).prop('disabled', false);
      $(this.enrolling_sel).prop('disabled', false);
      $(this.completed_sel).prop('checked', false);
      $(this.enrolling_sel).prop('checked', false);
      return $(this.modal_sel).addClass('btn-warning');
    }

    mark_unavailable() {
      this.completed = false;
      this.year_term_taken = false;
      this.enrolling = false;
      this.clear_formatting();
      $(this.completed_sel).prop('disabled', false);
      $(this.enrolling_sel).prop('disabled', true);
      $(this.completed_sel).prop('checked', false);
      $(this.enrolling_sel).prop('checked', false);
      return $(this.modal_sel).addClass('btn-secondary');
    }

    mark_completed(year_term) {
      var course, j, k, len, len1, ref, ref1, results;
      this.completed = true;
      this.year_term_taken = year_term;
      this.enrolling = false;
      this.clear_formatting();
      $(this.card_sel).addClass('border-success');
      $(this.header_sel).addClass('bg-success text-white');
      $(this.completed_sel).prop('checked', true);
      $(this.enrolling_sel).prop('checked', false);
      $(this.completed_sel).prop('disabled', false);
      $(this.enrolling_sel).prop('disabled', true);
      $(this.modal_sel).addClass('btn-success');
      ref = this.prereqs;
      for (j = 0, len = ref.length; j < len; j++) {
        course = ref[j];
        course.mark_completed(year_term);
      }
      ref1 = this.coreqs;
      results = [];
      for (k = 0, len1 = ref1.length; k < len1; k++) {
        course = ref1[k];
        results.push(course.mark_completed(year_term));
      }
      return results;
    }

    mark_enrolling(year_term) {
      this.completed = false;
      this.year_term_taken = year_term;
      this.enrolling = true;
      this.clear_formatting();
      $(this.card_sel).addClass('border-primary');
      $(this.header_sel).addClass('bg-primary text-white');
      $(this.completed_sel).prop('checked', false);
      $(this.enrolling_sel).prop('checked', true);
      $(this.completed_sel).prop('disabled', true);
      $(this.enrolling_sel).prop('disabled', false);
      return $(this.modal_sel).addClass('btn-primary');
    }

    refresh(old_year_term, new_year_term) {
      // moving to future year? convert class from enrolling to taken
      if (new_year_term.value() > old_year_term.value()) {
        if (this.enrolling) {
          this.mark_completed(old_year_term);
          $(this.enrolling_sel).prop('checked', this.enrolling);
          return $(this.completed_sel).prop('checked', this.completed);
        } else if (this.completed) {
          if (new_year_term.value() > this.year_term_taken.value()) {
            return this.mark_completed(this.year_term_taken);
          }
        } else if (this.available(new_year_term)) {
          return this.mark_available();
        } else {
          return this.mark_unavailable();
        }
      
      // staying in the same year-term (changed status of one course)
      } else if (new_year_term.value() === old_year_term.value()) {
        if (this.completed) {
          if (!this.year_term_taken) {
            // probably just marked completed; reflect in the data
            return this.mark_completed(old_year_term);
          } else {
            return this.mark_completed(this.year_term_taken);
          }
        } else if (this.enrolling) {
          return this.mark_enrolling(new_year_term);
        } else if (this.available(new_year_term)) {
          return this.mark_available();
        } else {
          return this.mark_unavailable();
        }
      } else {
        // going back in time; might need to unset date taken
        if (this.completed) {
          if (new_year_term.value() > this.year_term_taken.value()) {
            return this.mark_completed(this.year_term_taken);
          } else if (new_year_term.value() === this.year_term_taken.value()) {
            return this.mark_enrolling(this.year_term_taken);
          } else if (this.available(new_year_term)) {
            return this.mark_available();
          } else {
            return this.mark_unavailable();
          }
        // not completed, but it was marked enrolling? Then it isn't taken or
        // enrolled. Pretend it it never happened
        } else if (this.available(new_year_term)) {
          return this.mark_available();
        } else {
          return this.mark_unavailable();
        }
      }
    }

    add_coreq(new_coreq) {
      return this.coreqs.push(new_coreq);
    }

    add_prereq(new_prereq) {
      return this.prereqs.push(new_prereq);
    }

  };

  YearTerm = class YearTerm {
    constructor(year1, term1) {
      this.year = year1;
      this.term = term1;
    }

    value() {
      var res;
      res = this.year * 10;
      if (this.term === 'fall') {
        res += 5;
      }
      return res;
    }

  };

  
  // combine course data with the course class to make useful objects
  MATH_112 = new Course(course_data.MATH_112);

  MATH_114 = new Course(course_data.MATH_114);

  MATH_215 = new Course(course_data.MATH_215);

  MATH_216 = new Course(course_data.MATH_216);

  MATH_312 = new Course(course_data.MATH_312);

  PHYS_186 = new Course(course_data.PHYS_186);

  PHYS_231 = new Course(course_data.PHYS_231);

  PHYS_232 = new Course(course_data.PHYS_232);

  PHYS_240 = new Course(course_data.PHYS_240);

  PHYS_255 = new Course(course_data.PHYS_255);

  PHYS_332 = new Course(course_data.PHYS_332);

  PHYS_333 = new Course(course_data.PHYS_333);

  PHYS_340 = new Course(course_data.PHYS_340);

  PHYS_350 = new Course(course_data.PHYS_350);

  PHYS_356 = new Course(course_data.PHYS_356);

  PHYS_360 = new Course(course_data.PHYS_360);

  PHYS_361 = new Course(course_data.PHYS_361);

  PHYS_362 = new Course(course_data.PHYS_362);

  PHYS_363 = new Course(course_data.PHYS_363);

  PHYS_365 = new Course(course_data.PHYS_365);

  PHYS_367 = new Course(course_data.PHYS_367);

  PHYS_375 = new Course(course_data.PHYS_375);

  PHYS_430 = new Course(course_data.PHYS_430);

  PHYS_445 = new Course(course_data.PHYS_445);

  PHYS_465 = new Course(course_data.PHYS_465);

  PHYS_486 = new Course(course_data.PHYS_486);

  courses = [MATH_112, MATH_114, MATH_215, MATH_216, MATH_312, PHYS_186, PHYS_231, PHYS_232, PHYS_240, PHYS_255, PHYS_332, PHYS_333, PHYS_340, PHYS_350, PHYS_356, PHYS_360, PHYS_361, PHYS_362, PHYS_363, PHYS_365, PHYS_367, PHYS_375, PHYS_430, PHYS_445, PHYS_465, PHYS_486];

// firm up requirements so they work properly
  for (j = 0, len = courses.length; j < len; j++) {
    course = courses[j];
    course.update_requirements(courses);
  }

  today = new Date();

  current_year = today.getFullYear();

  current_month = today.getMonth();

  first_term = 'fall';

  second_term = 'spring';

  year_terms = [new YearTerm(current_year, 'spring'), new YearTerm(current_year, 'fall'), new YearTerm(current_year + 1, 'spring'), new YearTerm(current_year + 1, 'fall'), new YearTerm(current_year + 2, 'spring'), new YearTerm(current_year + 2, 'fall'), new YearTerm(current_year + 3, 'spring'), new YearTerm(current_year + 3, 'fall'), new YearTerm(current_year + 4, 'spring'), new YearTerm(current_year + 4, 'fall'), new YearTerm(current_year + 5, 'spring'), new YearTerm(current_year + 5, 'fall')];

  if (current_month < 5) {
    year_terms = year_terms.slice(0, 11);
  } else {
    year_terms = year_terms.slice(1, 12);
  }

  wizard = {
    year_term: year_terms[0],
    course_groups: [
      {
        title: 'Introductory and Prerequisite Courses',
        courses: [MATH_112,
      MATH_114,
      MATH_215,
      MATH_216,
      PHYS_186,
      PHYS_231,
      PHYS_232,
      PHYS_240]
      },
      {
        title: 'Intermediate Courses',
        courses: [MATH_312,
      PHYS_255,
      PHYS_332,
      PHYS_333,
      PHYS_340,
      PHYS_350,
      PHYS_361,
      PHYS_365,
      PHYS_367]
      },
      {
        title: 'Advanced Courses',
        courses: [PHYS_356,
      PHYS_375,
      PHYS_430,
      PHYS_445,
      PHYS_465,
      PHYS_486]
      }
    ],
    add_group: function(new_group) {
      var k, len1, ref, to_add;
      to_add = "<hr class='my-5'>\n";
      to_add += "<div class='row'><div class='col'>\n";
      to_add += `  <h2>${new_group.title}</h2>\n`;
      to_add += "</div></div>\n";
      to_add += "<div class='row'>\n";
      ref = new_group.courses;
      for (k = 0, len1 = ref.length; k < len1; k++) {
        course = ref[k];
        to_add += "  <div class='col-12 col-md-6 col-lg-4 col-xl-3 mb-3'>\n";
        to_add += `    ${course.html_card}`;
        to_add += "  </div>\n";
      }
      to_add += "</div>\n";
      return $('#body').append(to_add);
    },
    get_course: function(designation) {
      var field, k, len1, number;
      field = designation.split(' ')[0];
      number = Number(designation.split(' ')[1]);
      for (k = 0, len1 = courses.length; k < len1; k++) {
        course = courses[k];
        if (course.field === field && course.number === number) {
          return course;
        }
      }
    },
    refresh: function(old_year_term) {
      var k, len1, results;
      results = [];
      for (k = 0, len1 = courses.length; k < len1; k++) {
        course = courses[k];
        results.push(course.refresh(old_year_term, wizard.year_term));
      }
      return results;
    },
    setup: function() {
      var group, i, k, l, len1, ref, term, year;
// set up year-term selectors
      for (i = k = 0; k < 11; i = ++k) {
        year = year_terms[i].year;
        term = year_terms[i].term;
        $('#year-term-selector a#year-term-' + i.toString() + 'a').text(term.replace(/^\w/, (c) => {
          return c.toUpperCase();
        }) + ' ' + year);
      }
      $('ul#year-term-selector a').click(function(event) {
        var old_year_term, position;
        event.preventDefault();
        old_year_term = wizard.year_term;
        position = Number($(this).data('position'));
        wizard.year_term = year_terms[position];
        $('ul#year-term-selector li').removeClass('active');
        $('ul#year-term-selector li#year-term-' + position.toString()).addClass('active');
        return wizard.refresh(old_year_term);
      });
      ref = wizard.course_groups;
      for (l = 0, len1 = ref.length; l < len1; l++) {
        group = ref[l];
        wizard.add_group(group);
      }
      // activate switch listeners
      $('input.completed').click(function() {
        wizard.get_course(this.id.split('-').slice(0, 2).join(' ')).toggle_completed();
        return wizard.refresh(wizard.year_term);
      });
      $('input.enrolling').click(function() {
        wizard.get_course(this.id.split('-').slice(0, 2).join(' ')).toggle_enrolling();
        return wizard.refresh(wizard.year_term);
      });
      // activate modal description listeners
      $('button.description').click(function() {
        course = wizard.get_course(this.id.split('-').slice(0, 2).join(' '));
        course.update_modal(wizard.year_term);
        $('#course-info').modal();
        $('#modal-enrolling').click(function(event) {
          event.preventDefault;
          // leverage the fact that the title has the course name in it, with a
          // colon right after it. Janky, but it works for now!
          course = wizard.get_course($('#course-info-label').text().split(':')[0]);
          course.enrolling = true;
          course.completed = false;
          course.year_term_taken = false;
          wizard.refresh(wizard.year_term);
          return $('#course-info').modal('hide');
        });
        return $('#modal-completed').click(function(event) {
          event.preventDefault;
          // leverage the fact that the title has the course name in it, with a
          // colon right after it. Janky, but it works for now!
          course = wizard.get_course($('#course-info-label').text().split(':')[0]);
          course.enrolling = false;
          course.completed = true;
          wizard.refresh(wizard.year_term);
          return $('#course-info').modal('hide');
        });
      });
      // set up initial availability
      return wizard.refresh(wizard.year_term);
    }
  };

  $(document).ready(function() {
    return wizard.setup();
  });

}).call(this);
